/**
 * AutoVault dealer-dashboard Spanish dictionary.
 * Merged from checklist HTML + live dashboard extras.
 */
(function (g) {
  g.AV_DASH_ES = {
  "INVENTORY": "INVENTARIO",
  "DOCUMENTS": "DOCUMENTOS",
  "PAYROLL": "NÓMINA",
  "TOOLS": "HERRAMIENTAS",
  "SALES": "VENTAS",
  "FINANCIALS": "FINANZAS",
  "REPORTS": "REPORTES",
  "Dashboard": "Panel",
  "Vehicles": "Vehículos",
  "Vehicles by Profit": "Vehículos por Ganancia",
  "Vehicles by Loss": "Vehículos por Pérdida",
  "Profit & Loss": "Ganancias y Pérdidas",
  "Expenses": "Gastos",
  "Paid Customers": "Clientes Pagados",
  "Customers": "Clientes",
  "Deal Jackets": "Carpetas de Venta",
  "Files & Storage": "Archivos y Almacenamiento",
  "Payroll & Commissions": "Nómina y Comisiones",
  "Sales Reps": "Vendedores",
  "Calendar": "Calendario",
  "Reports & Reminders": "Reportes y Recordatorios",
  "State Tax": "Impuesto Estatal",
  "CPA Portal Login": "Acceso Portal CPA",
  "+ Add Vehicle": "+ Agregar Vehículo",
  "+ Add Expense": "+ Agregar Gasto",
  "Scan VIN": "Escanear VIN",
  "Mark Sold": "Marcar Vendido",
  "+ Add Customer": "+ Agregar Cliente",
  "⋯ More": "⋯ Más",
  "Dealer Admin": "Admin del Concesionario",
  "Search vehicles, VIN, customers...": "Buscar vehículos, VIN, clientes...",
  "PAID CUSTOMERS": "CLIENTES PAGADOS",
  "PROFIT & LOSS": "GANANCIAS Y PÉRDIDAS",
  "VEHICLES BY PROFIT": "VEHÍCULOS POR GANANCIA",
  "VEHICLES BY LOSS": "VEHÍCULOS POR PÉRDIDA",
  "EXPENSES": "GASTOS",
  "PAYROLL & COMMISSIONS": "NÓMINA Y COMISIONES",
  "DEAL JACKETS": "CARPETAS DE VENTA",
  "SALES REPS": "VENDEDORES",
  "FLOORING BREAKDOWN": "DESGLOSE DE FINANCIAMIENTO",
  "Total Revenue": "Ingresos Totales",
  "Gross Profit": "Ganancia Bruta",
  "Net Profit": "Ganancia Neta",
  "Net Loss": "Pérdida Neta",
  "Total Expenses": "Gastos Totales",
  "Total Cost": "Costo Total",
  "Total Vehicle Cost": "Costo Total del Vehículo",
  "Vehicle Cost": "Costo del Vehículo",
  "Sold Price": "Precio de Venta",
  "Purchase Price": "Precio de Compra",
  "Vehicle Sold Price": "Precio de Venta del Vehículo",
  "Vehicle Purchase Price": "Precio de Compra del Vehículo",
  "Commission": "Comisión",
  "Commissions": "Comisiones",
  "Sales Commissions": "Comisiones de Venta",
  "Repairs": "Reparaciones",
  "Repairs / Expenses": "Reparaciones / Gastos",
  "Fees": "Cargos",
  "Flooring": "Financiamiento de Piso",
  "Flooring Cost": "Costo de Financiamiento",
  "Total Flooring Cost": "Costo Total de Financiamiento",
  "Add-Ons": "Extras",
  "Add-On Revenue": "Ingresos por Extras",
  "Sales Tax": "Impuesto de Venta",
  "Registration Fees": "Cargos de Registro",
  "Registration Fee ($)": "Cargo de Registro ($)",
  "Total Amount Collected": "Monto Total Cobrado",
  "Total Purchase Value": "Valor Total de Compra",
  "Average Purchase": "Compra Promedio",
  "Total Inventory": "Inventario Total",
  "Purchase Cost": "Costo de Compra",
  "Total Fees": "Cargos Totales",
  "Total Repairs": "Reparaciones Totales",
  "Upcoming Floored": "Financiados Próximos",
  "Vehicles at a Loss": "Vehículos en Pérdida",
  "Total Net Loss": "Pérdida Neta Total",
  "Average Loss": "Pérdida Promedio",
  "Average ROI %": "ROI Promedio %",
  "Total Profitable Vehicles": "Vehículos Rentables Totales",
  "Total Net Profit": "Ganancia Neta Total",
  "Sold This Month": "Vendidos Este Mes",
  "Titles": "Títulos",
  "Deals Closed": "Ventas Cerradas",
  "Total Sold Value": "Valor Total Vendido",
  "Avg ROI": "ROI Prom.",
  "Vehicles Floored": "Vehículos Financiados",
  "Flooring Fees Owed": "Cargos de Financiamiento Adeudados",
  "Owed to Flooring Co.": "Adeudado a la Financiera",
  "Coming Up for Payoff": "Próximos a Liquidar",
  "Total Payroll": "Nómina Total",
  "Wages & Salary": "Sueldos y Salarios",
  "Headcount": "Personal",
  "Team Payroll": "Nómina del Equipo",
  "Customer Directory": "Directorio de Clientes",
  "Revenue Allocation": "Distribución de Ingresos",
  "Profit & Loss Statement": "Estado de Ganancias y Pérdidas",
  "How Net Profit Was Calculated": "Cómo se Calculó la Ganancia Neta",
  "Where the Money Goes": "A Dónde Va el Dinero",
  "Where You're Losing": "Dónde Estás Perdiendo",
  "Rest of Inventory": "Resto del Inventario",
  "Other Paid Customers": "Otros Clientes Pagados",
  "Underwater Vehicles": "Vehículos en Números Rojos",
  "Floored Vehicles": "Vehículos Financiados",
  "All Sales Reps": "Todos los Vendedores",
  "Cost of Goods Sold": "Costo de Ventas",
  "Revenue": "Ingresos",
  "Operating Expenses": "Gastos Operativos",
  "Sale Information": "Información de Venta",
  "Customer Information": "Información del Cliente",
  "Cost Breakdown": "Desglose de Costos",
  "Sales Rep & Commission": "Vendedor y Comisión",
  "Add-On Upcharges": "Cargos por Extras",
  "Documents": "Documentos",
  "Deal Notes": "Notas de Venta",
  "Full Name": "Nombre Completo",
  "Cell Phone": "Teléfono Celular",
  "Email": "Correo",
  "Address": "Dirección",
  "Sale Date": "Fecha de Venta",
  "Deal Number": "Número de Venta",
  "State Sales Tax ($)": "Impuesto de Venta Estatal ($)",
  "Sold Price ($)": "Precio de Venta ($)",
  "Sales Rep": "Vendedor",
  "Commission %": "Comisión %",
  "Or Commission $": "O Comisión $",
  "Commission owed to rep": "Comisión adeudada al vendedor",
  "Save Deal & Mark Sold": "Guardar Venta y Marcar Vendido",
  "Choose another vehicle": "Elegir otro vehículo",
  "Back to Paid Customers": "Volver a Clientes Pagados",
  "Scan Document": "Escanear Documento",
  "Scan / Upload ID": "Escanear / Subir ID",
  "Purchase Agreement": "Contrato de Compra",
  "Title": "Título",
  "Odometer Statement": "Declaración de Odómetro",
  "Bill of Sale": "Factura de Venta",
  "Insurance": "Seguro",
  "Registration": "Registro",
  "Payment Method": "Método de Pago",
  "Category": "Categoría",
  "Amount": "Monto",
  "Due Date": "Fecha de Vencimiento",
  "Frequency": "Frecuencia",
  "Notes": "Notas",
  "Status": "Estado",
  "Paid": "Pagado",
  "Unpaid": "No Pagado",
  "Attach to vehicle": "Adjuntar a vehículo",
  "Add Expense": "Agregar Gasto",
  "Edit Expense": "Editar Gasto",
  "Employee": "Empleado",
  "Role": "Rol",
  "Pay Type": "Tipo de Pago",
  "Basis": "Base",
  "Earnings": "Ganancias",
  "Add Employee": "Agregar Empleado",
  "Edit Employee": "Editar Empleado",
  "Add Sales Rep": "Agregar Vendedor",
  "Salary": "Salario",
  "Hourly": "Por Hora",
  "Name": "Nombre",
  "Monthly Salary ($)": "Salario Mensual ($)",
  "Hourly Rate ($)": "Tarifa por Hora ($)",
  "Hours / Month": "Horas / Mes",
  "Commission Rate (% of gross)": "Tasa de Comisión (% del bruto)",
  "Customer": "Cliente",
  "Phone": "Teléfono",
  "Vehicle Purchased": "Vehículo Comprado",
  "Purchased": "Comprado",
  "Sale Price": "Precio de Venta",
  "Vehicle": "Vehículo",
  "Actions": "Acciones",
  "Days on Lot": "Días en el Lote",
  "Sales Rep ": "Vendedor ",
  "ROI %": "ROI %",
  "Gross": "Bruto",
  "Date": "Fecha",
  "Save": "Guardar",
  "Cancel": "Cancelar",
  "Delete": "Eliminar",
  "Remove": "Quitar",
  "Got it": "Entendido",
  "Exit": "Salir",
  "Save Rep": "Guardar Vendedor",
  "Print / Export": "Imprimir / Exportar",
  "Monthly": "Mensual",
  "Yearly": "Anual",
  "View Flooring Cost": "Ver Costo de Financiamiento",
  "Mark Paid Off": "Marcar Liquidado",
  "Top Sales Rep": "Mejor Vendedor",
  "Cars Sold": "Autos Vendidos",
  "Avg / Deal": "Prom. / Venta",
  "View details →": "Ver detalles →",
  "View deal jacket →": "Ver carpeta de venta →",
  "Appearance": "Apariencia",
  "Language": "Idioma",
  "Dark or light theme": "Tema oscuro o claro",
  "Settings": "Ajustes",
  "Numbers stay the same; only wording changes.": "Los números no cambian; solo cambia el texto.",
  "Acquisition & Cost Breakdown": "Adquisición y Desglose de Costos",
  "Vehicle Acquisition": "Adquisición del Vehículo",
  "Sale & Profit": "Venta y Ganancia",
  "+ Add Previous Sold Vehicle": "+ Agregar Vehículo Vendido Anteriormente",
  "Add Previous Sold Vehicle": "Agregar Vehículo Vendido Anteriormente",
  "Available": "Disponible",
  "All": "Todos",
  "Sold": "Vendido",
  "Sold Vehicles": "Vehículos Vendidos",
  "Sold Vehicles by Month": "Vehículos Vendidos por Mes",
  "Sort: Default": "Orden: Predeterminado",
  "Net Profit (high → low)": "Ganancia Neta (mayor → menor)",
  "ROI (high → low)": "ROI (mayor → menor)",
  "Days in Inventory (high → low)": "Días en Inventario (mayor → menor)",
  "Flooring Cost (high → low)": "Costo de Financiamiento (mayor → menor)",
  "Add Grid Lines": "Agregar Líneas de Cuadrícula",
  "Remove Grid Lines": "Quitar Líneas de Cuadrícula",
  "Vehicles by Month": "Vehículos por Mes",
  "Available Inventory": "Inventario Disponible",
  "All-In Vehicle Cost": "Costo Total del Vehículo",
  "Profit This Month": "Ganancia Este Mes",
  "available inventory": "inventario disponible",
  "all vehicles": "todos los vehículos",
  "sold vehicles": "vehículos vendidos",
  "Costs ·": "Costos ·",
  "spent on current stock": "gastado en stock actual",
  "recon + parts": "recon + partes",
  "collected this period": "cobrado este periodo",
  "owed to reps": "adeudado a vendedores",
  "all-in on current stock": "total en stock actual",
  "net, sold this month": "neto, vendido este mes",
  "Search vehicles, VIN, or rep…": "Buscar vehículos, VIN o vendedor…",
  "Add Vehicle": "Agregar Vehículo",
  "Scan VIN number": "Escanear número VIN",
  "Or paste / type the VIN": "O pegue / escriba el VIN",
  "Add without VIN number": "Agregar sin número VIN",
  "Add with VIN number": "Agregar con número VIN",
  "Year": "Año",
  "Make": "Marca",
  "Model": "Modelo",
  "Purchase Date": "Fecha de Compra",
  "Dates": "Fechas",
  "Acquisition & Costs": "Adquisición y Costos",
  "Sale": "Venta",
  "Purchase Price ($)": "Precio de Compra ($)",
  "Auction Fees ($)": "Cargos de Subasta ($)",
  "Auction / Doc Fees ($)": "Cargos de Subasta / Doc ($)",
  "Repairs / Recon ($)": "Reparaciones / Recon ($)",
  "Other Expenses ($)": "Otros Gastos ($)",
  "Flooring Cost ($)": "Costo de Financiamiento ($)",
  "Purchase Location": "Lugar de Compra",
  "Sale Price ($)": "Precio de Venta ($)",
  "Sales Tax Collected ($)": "Impuesto de Venta Cobrado ($)",
  "Registration Fees ($)": "Cargos de Registro ($)",
  "Commission ($)": "Comisión ($)",
  "Add Flooring Rate": "Agregar Tasa de Financiamiento",
  "Add Vehicle to Inventory": "Agregar Vehículo al Inventario",
  "Save to Sold Vehicles": "Guardar en Vehículos Vendidos",
  "+ Add add-on": "+ Agregar extra",
  "Leave blank for none": "Deje en blanco si no aplica",
  "Blank = auto-calculate": "En blanco = cálculo automático",
  "Pick an auction or type your own": "Elija una subasta o escriba la suya",
  "Is the title present for this vehicle?": "¿Está presente el título de este vehículo?",
  "Yes, title is in": "Sí, el título está",
  "No, not yet": "No, todavía no",
  "Save this vehicle without a VIN?": "¿Guardar este vehículo sin VIN?",
  "Yes, save without VIN": "Sí, guardar sin VIN",
  "No, I'll add it": "No, lo agregaré",
  "17-digit VIN…": "VIN de 17 dígitos…",
  "Payment Settings": "Configuración de Pagos",
  "Contact Support": "Contactar Soporte",
  "Owner Login": "Acceso del Dueño",
  "Review Notes": "Notas de Revisión",
  "Log Out": "Cerrar Sesión",
  "Financials": "Finanzas",
  "Payroll": "Nómina",
  "Tools": "Herramientas",
  "CPA Tools": "Herramientas CPA",
  "Inventory": "Inventario",
  "SALES TAX": "IMPUESTO DE VENTA",
  "Sales Tax Filing Schedule": "Calendario de Declaración de Impuestos",
  "Quarterly Filing": "Declaración Trimestral",
  "Monthly Filing": "Declaración Mensual",
  "Semi-Annual Filing": "Declaración Semestral",
  "Annual Filing": "Declaración Anual",
  "Mark as Filed": "Marcar como Declarado",
  "Edit Filing Schedule": "Editar Calendario",
  "Total Sales Tax": "Impuesto de Venta Total",
  "Taxable Sales": "Ventas Gravables",
  "total sold value": "valor total vendido",
  "in this period": "en este periodo",
  "Next Filing": "Próxima Declaración",
  "set a due date": "fije una fecha de vencimiento",
  "Sales Tax by Vehicle": "Impuesto de Venta por Vehículo",
  "Tax by Month": "Impuesto por Mes",
  "Show Quarterly Filings": "Mostrar Declaraciones Trimestrales",
  "Show Monthly Filings": "Ver Declaraciones Mensuales",
  "Show Semi-Annual Filings": "Ver Declaraciones Semestrales",
  "Show Annual Filings": "Ver Declaraciones Anuales",
  "Show Flat List": "Ver Lista Simple",
  "Filing History": "Historial de Declaraciones",
  "Export CSV": "Exportar CSV",
  "Sold Date": "Fecha de Venta",
  "Rate": "Tasa",
  "SOLD VEHICLES": "VEHÍCULOS VENDIDOS",
  "Sold History": "Historial de Ventas",
  "Vehicle History": "Historial del Vehículo",
  "PAYMENT SETTINGS": "AJUSTES DE PAGO",
  "ACCOUNT": "CUENTA",
  "Current Plan": "Plan Actual",
  "Upgrade Plan": "Mejorar Plan",
  "Update Payment Method": "Actualizar Método de Pago",
  "Make a Payment": "Hacer un Pago",
  "Add Payments to Expenses Automatically": "Agregar Pagos a Gastos Automáticamente",
  "Signed Agreement": "Acuerdo Firmado",
  "Billing History": "Historial de Facturación",
  "CALENDAR": "CALENDARIO",
  "View Flooring Calendar": "Ver Calendario de Financiamiento",
  "View Sales Calendar": "Ver Calendario de Ventas",
  "Sales Calendar": "Calendario de Ventas",
  "Flooring Calendar": "Calendario de Financiamiento",
  "How much did it sell for? ($)": "¿En cuánto se vendió? ($)",
  "The Sale": "La Venta",
  "Deal Type / Status": "Tipo de Venta / Estado",
  "Arbitration": "Arbitraje",
  "Sold at a Loss": "Vendido con Pérdida",
  "Wholesale": "Mayoreo",
  "Out of State Sale": "Venta Fuera del Estado",
  "Financing": "Financiamiento",
  "optional": "opcional",
  "Net Check ($)": "Cheque Neto ($)",
  "Collected for State": "Cobrado para el Estado",
  "pass-through": "traspaso",
  "Your profit on this deal": "Tu ganancia en esta venta",
  "click any figure to edit": "haga clic en cualquier cifra para editar",
  "Standard sale by default. Pick Arbitration, Sold at a Loss, Wholesale, or Out of State to open its details.": "Venta estándar por defecto. Elija Arbitraje, Vendido con Pérdida, Mayoreo o Fuera del Estado para abrir sus detalles.",
  "Your Name": "Su Nombre",
  "Topic": "Tema",
  "Subject": "Asunto",
  "Priority": "Prioridad",
  "Low": "Baja",
  "Normal": "Normal",
  "Urgent": "Urgente",
  "Message": "Mensaje",
  "Send Message": "Enviar Mensaje",
  "Done": "Listo",
  "Technical issue": "Problema técnico",
  "Billing & payments": "Facturación y pagos",
  "Feature request": "Solicitud de función",
  "Bug report": "Reporte de error",
  "Account / login": "Cuenta / acceso",
  "Titles Present": "Títulos Presentes",
  "in-stock · click to filter": "en stock · clic para filtrar",
  "All Vehicles": "Todos los Vehículos",
  "By Profit": "Por Ganancia",
  "By Loss": "Por Pérdida",
  "Vehicle Sales": "Ventas de Vehículos",
  "Add-On & Upcharge Revenue": "Ingresos por Extras y Recargos",
  "Auction & Title Fees": "Cargos de Subasta y Título",
  "Reconditioning & Repairs": "Reacondicionamiento y Reparaciones",
  "Floor-Plan (Flooring)": "Plan de Piso (Financiamiento)",
  "Vehicle Expenses": "Gastos de Vehículos",
  "Add-On Cost": "Costo de Extras",
  "Total COGS": "Costo de Ventas Total",
  "Sales Commissions & Payroll": "Comisiones de Venta y Nómina",
  "Recurring Expenses": "Gastos Recurrentes",
  "Dealership Expenses": "Gastos del Concesionario",
  "Total Operating Expenses": "Gastos Operativos Totales",
  "view": "ver",
  "view all →": "ver todo →",
  "Sold / Ask": "Vendido / Pedido",
  "Sun": "Dom",
  "Mon": "Lun",
  "Tue": "Mar",
  "Wed": "Mié",
  "Thu": "Jue",
  "Fri": "Vie",
  "Sat": "Sáb",
  "January": "Enero",
  "February": "Febrero",
  "March": "Marzo",
  "April": "Abril",
  "May": "Mayo",
  "June": "Junio",
  "July": "Julio",
  "August": "Agosto",
  "September": "Septiembre",
  "October": "Octubre",
  "November": "Noviembre",
  "December": "Diciembre",
  "Jan": "Ene",
  "Apr": "Abr",
  "Aug": "Ago",
  "Dec": "Dic",
  "Search vehicles, VIN, customers, jackets…": "Buscar vehículos, VIN, clientes, jackets…",
  "Sold Value": "Valor Vendido",
  "units sold": "unidades vendidas",
  "units moved": "unidades movidas",
  "This Month": "Este Mes",
  "Total Vehicles": "Vehículos Totales",
  "on the lot now": "en el lote ahora",
  "Flooring rate system": "Sistema de tasa de financiamiento",
  "Add Flooring Rate to System": "Agregar Tasa de Financiamiento al Sistema",
  "Browse sold history": "Explorar historial de ventas",
  "vehicles on lot": "vehículos en el lote",
  "vehicles in current inventory": "vehículos en inventario actual",
  "Profit Calculator": "Calculadora de Ganancia",
  "Set Status…": "Definir Estado…",
  "Open Deal Jacket →": "Abrir Carpeta de Venta →",
  "Fill in the sale below — your profit updates live as you type.": "Completa la venta abajo — tu ganancia se actualiza al escribir.",
  "No commission · $0": "Sin comisión · $0",
  "You're in at": "Estás invertido en",
  "If you sell for": "Si vendes por",
  "Projected profit": "Ganancia proyectada",
  "Purchase price": "Precio de compra",
  "Other expenses": "Otros gastos",
  "No itemized costs yet": "Aún no hay costos desglosados",
  "Enter a target sale price to see your projected profit.": "Ingresa un precio de venta para ver la ganancia proyectada.",
  "Enter a sale price of $0 or more.": "Ingresa un precio de venta de $0 o más.",
  "Bright mode": "Modo claro",
  "Dark / Bright theme": "Tema oscuro / claro",
  "Switch to bright mode": "Cambiar a modo claro",
  "Switch to dark mode": "Cambiar a modo oscuro",
  "Flooring Rate System": "Sistema de Tasa de Financiamiento",
  "Floor-plan interest, tracked per vehicle": "Interés del plan de piso, rastreado por vehículo",
  "Remove From All": "Quitar de Todos",
  "Sort": "Ordenar",
  "Add Previous Sold": "Agregar Vendido Anterior",
  "Success": "Éxito",
  "Warning": "Advertencia",
  "Something went wrong": "Algo salió mal",
  "Working": "Trabajando",
  "Notice": "Aviso",
  "Please wait": "Por favor espera",
  "Saving…": "Guardando…",
  "Deal saved": "Venta guardada",
  "Deal jacket created": "Carpeta de venta creada",
  "Repair saved": "Reparación guardada",
  "Repair removed": "Reparación eliminada",
  "Failed to save repair": "No se pudo guardar la reparación",
  "Failed to delete repair": "No se pudo eliminar la reparación",
  "Flooring rates cannot be negative": "Las tasas de financiamiento no pueden ser negativas",
  "Description and price are required": "Se requieren descripción y precio",
  "Purchase date updated": "Fecha de compra actualizada",
  "Saved": "Guardado",
  "Save failed": "Error al guardar",
  "Failed to save deal": "No se pudo guardar la venta",
  "Failed to save rep": "No se pudo guardar el vendedor",
  "Close": "Cerrar",
  "Click Add Repair (or Update Repair) first, then Save": "Haz clic en Agregar Reparación (o Actualizar) primero, luego Guardar",
  "Welcome back": "Bienvenido de nuevo",
  "Welcome back,": "Bienvenido de nuevo,",
  "Welcome back, ": "Bienvenido de nuevo, ",
  ". Here is your month at a glance.": ". Aquí tienes tu mes de un vistazo.",
  "Vehicles Sold": "Vehículos Vendidos",
  "this month": "este mes",
  "before costs": "antes de costos",
  "after all costs": "después de todos los costos",
  "Owed to Reps": "Adeudado a Vendedores",
  "commission this month": "comisión este mes",
  "Total Invested": "Total Invertido",
  "in vehicles sold": "en vehículos vendidos",
  "sold vehicles": "vehículos vendidos",
  "gross sales": "ventas brutas",
  "across deals": "en todas las ventas",
  "in this period": "en este periodo",
  "Accountant full name": "Nombre completo del contador",
  "Add sticky note": "Agregar nota adhesiva",
  "Additional notes": "Notas adicionales",
  "Any notes about this funding check…": "Notas sobre este cheque de financiamiento…",
  "Ask Jenna anything...": "Pregúntale lo que quieras a Jenna...",
  "Ask Jenna — drag to move": "Pregunta a Jenna — arrastra para mover",
  "Attach a vehicle": "Adjuntar un vehículo",
  "Attached Vehicle": "Vehículo Adjunto",
  "Back to auto-calculated": "Volver al cálculo automático",
  "Brief summary — e.g. Can't mark a vehicle sold": "Resumen breve — ej. No puedo marcar un vehículo vendido",
  "Buyer / dealer name": "Nombre del comprador / concesionario",
  "Calculated after an actual sale price is entered": "Calculado después de ingresar un precio de venta real",
  "Calculator": "Calculadora",
  "Change number color": "Cambiar color del número",
  "Choose which vehicles the spreadsheet shows": "Elija qué vehículos muestra la hoja",
  "City": "Ciudad",
  "Clear net check and use sold-price profit": "Borrar cheque neto y usar ganancia por precio vendido",
  "Click for flooring": "Clic para financiamiento",
  "Click for repairs": "Clic para reparaciones",
  "Click to change the purchase date": "Clic para cambiar la fecha de compra",
  "Click to collapse this column": "Clic para contraer esta columna",
  "Click to cycle: titles present → titles missing → all": "Clic para alternar: títulos presentes → faltantes → todos",
  "Click to edit": "Clic para editar",
  "Click to edit attached expenses": "Clic para editar gastos adjuntos",
  "Click to edit purchase date": "Clic para editar fecha de compra",
  "Click to edit rep & commission": "Clic para editar vendedor y comisión",
  "Click to edit repair items": "Clic para editar reparaciones",
  "Click to enter actual net check from finance": "Clic para ingresar cheque neto real del financiamiento",
  "Click to minimize / expand": "Clic para minimizar / expandir",
  "Click to see vehicles due for flooring payoff": "Clic para ver vehículos próximos a liquidar",
  "Click to set your target sale price": "Clic para fijar su precio objetivo de venta",
  "Click to view present titles": "Clic para ver títulos presentes",
  "Click to view repairs & attached expenses": "Clic para ver reparaciones y gastos adjuntos",
  "Collapse sidebar": "Contraer barra lateral",
  "Contact name": "Nombre de contacto",
  "Cost of available inventory": "Costo del inventario disponible",
  "Create a strong password": "Cree una contraseña segura",
  "Current password": "Contraseña actual",
  "Customer full name": "Nombre completo del cliente",
  "Dark / Bright": "Oscuro / Claro",
  "Days in Inventory": "Días en Inventario",
  "Dealer #": "N.º de concesionario",
  "Dealership / business name": "Nombre del concesionario / negocio",
  "Dealership Expense": "Gasto del Concesionario",
  "Dealership name": "Nombre del concesionario",
  "Description": "Descripción",
  "Dismiss": "Descartar",
  "Edit": "Editar",
  "Edit rate": "Editar tasa",
  "English / Español": "English / Español",
  "Enter lender name": "Ingrese nombre del prestamista",
  "Filter by expense or note...": "Filtrar por gasto o nota...",
  "Filter by expense, vehicle, or note...": "Filtrar por gasto, vehículo o nota...",
  "Flat dollar amount per deal": "Monto fijo en dólares por venta",
  "Full Contact on File": "Contacto Completo en Archivo",
  "Full legal name": "Nombre legal completo",
  "Full name": "Nombre completo",
  "Generate a unique DL-##### deal number": "Generar un número de venta DL-##### único",
  "Inventory Cost": "Costo de Inventario",
  "Language / Idioma — switch to Español": "Language / Idioma — cambiar a Español",
  "Leads": "Prospectos",
  "Log in as this rep": "Iniciar sesión como este vendedor",
  "Look up VIN or vehicle...": "Buscar VIN o vehículo...",
  "Manheim, ADESA, dealer trade, private…": "Manheim, ADESA, intercambio, particular…",
  "Manheim, ADESA, etc.": "Manheim, ADESA, etc.",
  "Mark all as read": "Marcar todo como leído",
  "Mark vehicle as sold to enable Registration Fees": "Marque el vehículo vendido para habilitar cargos de registro",
  "Monthly Impact": "Impacto Mensual",
  "Net Salary": "Salario Neto",
  "New message": "Nuevo mensaje",
  "Next month": "Mes siguiente",
  "Next year": "Año siguiente",
  "Notes about this vehicle…": "Notas sobre este vehículo…",
  "Notes for this day…": "Notas para este día…",
  "Notifications": "Notificaciones",
  "Open in Flooring Breakdown": "Abrir en Desglose de Financiamiento",
  "Open this expense": "Abrir este gasto",
  "Open vehicle — this cost is in its P&L": "Abrir vehículo — este costo está en su G&P",
  "Optional — vendor, reference #, context": "Opcional — proveedor, referencia #, contexto",
  "Paid This Month": "Pagado Este Mes",
  "Paid This Year": "Pagado Este Año",
  "Password": "Contraseña",
  "Paste or type a VIN to attach": "Pegue o escriba un VIN para adjuntar",
  "Pay Breakdown": "Desglose de Pago",
  "Pay Schedule": "Calendario de Pago",
  "Payment History": "Historial de Pagos",
  "Payroll & Commission": "Nómina y Comisión",
  "Percentage of gross": "Porcentaje del bruto",
  "Pick date": "Elegir fecha",
  "Previous month": "Mes anterior",
  "Previous year": "Año anterior",
  "ROI": "ROI",
  "Re-enter new password": "Vuelva a ingresar la contraseña",
  "Reassign sales rep": "Reasignar vendedor",
  "Receipt": "Recibo",
  "Recurring Expense": "Gasto Recurrente",
  "Remove document": "Eliminar documento",
  "Revert to previous value": "Revertir al valor anterior",
  "Revert to your previous value": "Revertir a su valor anterior",
  "Sales tax collected this filing period — click for the full breakdown": "Impuesto cobrado en este periodo — clic para ver desglose completo",
  "Scan a document": "Escanear un documento",
  "Search conversations": "Buscar conversaciones",
  "Search customers, phone, email, VIN…": "Buscar clientes, teléfono, correo, VIN…",
  "Search leads by name, phone, email…": "Buscar prospectos por nombre, teléfono, correo…",
  "Search user, dealership, or state…": "Buscar usuario, concesionario o estado…",
  "Search vehicle or VIN…": "Buscar vehículo o VIN…",
  "Select a conversation to start messaging": "Seleccione una conversación para enviar mensajes",
  "Select or type a rep…": "Seleccione o escriba un vendedor…",
  "Send": "Enviar",
  "Show All-In + Flooring": "Mostrar Total + Financiamiento",
  "Show Flooring Age": "Mostrar Antigüedad de Financiamiento",
  "Show Flooring Cost": "Mostrar Costo de Financiamiento",
  "Show Potential Profit": "Mostrar Ganancia Potencial",
  "Show all deal jackets, or filter to a single month": "Mostrar todas las carpetas o filtrar por un mes",
  "Show all expenses": "Mostrar todos los gastos",
  "Stop": "Detener",
  "Stop or edit recurring expenses": "Detener o editar gastos recurrentes",
  "Street address": "Dirección",
  "Street, City, State ZIP": "Calle, Ciudad, Estado CP",
  "Tell us what's going on and how we can help…": "Cuéntenos qué ocurre y cómo podemos ayudar…",
  "Total Gross": "Bruto Total",
  "Total Net": "Neto Total",
  "Total Sales": "Ventas Totales",
  "Trade-in details, financing terms, promises made, follow-ups…": "Detalles de permuta, financiamiento, promesas, seguimientos…",
  "Type notes about this vehicle…": "Escriba notas sobre este vehículo…",
  "Type notes for this day…": "Escriba notas para este día…",
  "Type your own description": "Escriba su propia descripción",
  "Update vehicle status": "Actualizar estado del vehículo",
  "Users & access": "Usuarios y acceso",
  "Vehicle Expense": "Gasto del Vehículo",
  "View": "Ver",
  "View dealership expenses only": "Ver solo gastos del concesionario",
  "View every operating expense in this period, including recurring": "Ver todos los gastos operativos del periodo, incluidos recurrentes",
  "View payroll & commission only": "Ver solo nómina y comisión",
  "View receipt": "Ver recibo",
  "View recurring expenses only": "Ver solo gastos recurrentes",
  "View vehicle expenses only": "Ver solo gastos del vehículo",
  "What are they interested in?": "¿En qué están interesados?",
  "Write a review note or question for the dealer...": "Escriba una nota o pregunta para el concesionario...",
  "Write notes for this day...": "Escriba notas para este día...",
  "Your name": "Su nombre",
  "accrued interest to date": "interés acumulado a la fecha",
  "all-in cost": "costo total",
  "annualized": "anualizado",
  "auto": "automático",
  "before commission": "antes de comisión",
  "billing cycle": "ciclo de facturación",
  "click to view present titles": "clic para ver títulos presentes",
  "due soon or overdue": "próximo a vencer o vencido",
  "earned from deals": "ganado en ventas",
  "earned this period": "ganado en este periodo",
  "expense total": "total de gastos",
  "floored 30+ days · pay off soon": "financiado 30+ días · liquidar pronto",
  "greater of base / commission": "mayor entre base / comisión",
  "loading…": "cargando…",
  "on the floor plan": "en el plan de piso",
  "on the team": "en el equipo",
  "per customer": "por cliente",
  "phone & email captured": "teléfono y correo registrados",
  "principal + fees to clear": "capital + cargos por liquidar",
  "return on cost": "retorno sobre costo",
  "sold value": "valor vendido",
  "sold − purchase": "vendido − compra",
  "staff (hourly + salary)": "personal (por hora + salario)",
  "sum of what they paid": "suma de lo que pagaron",
  "this period": "este periodo",
  "to customer": "al cliente",
  "total sale price": "precio total de venta",
  "vehicle sales + add-ons": "ventas de vehículos + extras",
  "vehicles sold to buyers": "vehículos vendidos a compradores",
  "— gross margin": "— margen bruto",
  "— net margin": "— margen neto",
  "Profitable Sales": "Ventas Rentables",
  "Loss Sales": "Ventas con Pérdida",
  "My Leads": "Mis Prospectos",
  "Customer Leads": "Prospectos de Clientes",
  "Loading inventory…": "Cargando inventario…",
  "Loading sales…": "Cargando ventas…",
  "Has sales activity": "Tiene actividad de ventas",
  "No sales this month": "Sin ventas este mes",
  "And happy birthday to you! 🎉": "¡Y feliz cumpleaños para usted! 🎉",
  "You're doing well this month.": "Le va bien este mes.",
  "Looks like this'll be a profitable month.": "Parece que será un mes rentable.",
  "Let's keep an eye on the margins this month.": "Vigilemos los márgenes este mes.",
  "Let me know if there's anything I can help you with.": "Avíseme si puedo ayudarle en algo.",
  "Full Year": "Año Completo",
  "Financials · this vs last": "Finanzas · este vs anterior",
  "Compare": "Comparar",
  "vs last month": "vs mes anterior",
  "vs last year": "vs año anterior",
  "No vehicles in inventory yet.": "Aún no hay vehículos en inventario.",
  "No repair entries yet. Add the first one below.": "Aún no hay reparaciones. Agregue la primera abajo.",
  "Enter a description, then click + Add Repair or Save.": "Ingrese una descripción, luego + Agregar Reparación o Guardar.",
  "Update Repair": "Actualizar Reparación",
  "+ Add Repair": "+ Agregar Reparación",
  "Failed to load inventory. Check your connection and try again.": "No se pudo cargar el inventario. Revise su conexión e intente de nuevo.",
  "in active inventory": "en inventario activo",
  "Present": "Presente",
  "Missing": "Faltante",
  "Pending": "Pendiente",
  "Active": "Activo",
  "In Stock": "En Stock",
  "Converted": "Convertido",
  "Lost": "Perdido",
  "New": "Nuevo",
  "Contacted": "Contactado",
  "Qualified": "Calificado",
  "Standard": "Estándar",
  "One-time": "Única vez",
  "Recurring": "Recurrente",
  "Messages": "Mensajes",
  "Global Search": "Búsqueda Global",
  "Change Password": "Cambiar Contraseña",
  "Terms of Service": "Términos de Servicio",
  "Privacy Policy": "Política de Privacidad",
  "You're up ": "Subió ",
  "You're down ": "Bajó ",
  "% from last month.": "% respecto al mes anterior.",
  "&mdash; gross margin": "— margen bruto",
  "&mdash; net margin": "— margen neto",
  "Optional &mdash; vendor, reference #, context": "Opcional — proveedor, referencia #, contexto",
  "Notes for this day\u2026": "Notas para este día…",
  "Type notes for this day\u2026": "Escriba notas para este día…",
  "Manheim, ADESA, dealer trade, private\u2026": "Manheim, ADESA, intercambio, particular…"
};
  g.AV_MONTH_EN2ES = {
  "January": "Enero",
  "February": "Febrero",
  "March": "Marzo",
  "April": "Abril",
  "May": "Mayo",
  "June": "Junio",
  "July": "Julio",
  "August": "Agosto",
  "September": "Septiembre",
  "October": "Octubre",
  "November": "Noviembre",
  "December": "Diciembre",
  "Jan": "Ene",
  "Feb": "Feb",
  "Mar": "Mar",
  "Apr": "Abr",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Ago",
  "Sep": "Sep",
  "Sept": "Sep",
  "Oct": "Oct",
  "Nov": "Nov",
  "Dec": "Dic"
};
  g.AV_MONTH_ES2EN = (function () {
    var o = {};
    for (var k in g.AV_MONTH_EN2ES) {
      if (o[g.AV_MONTH_EN2ES[k]] === undefined) o[g.AV_MONTH_EN2ES[k]] = k;
    }
    return o;
  })();
})(typeof window !== "undefined" ? window : globalThis);
