/**
 * AutoVault dealer-dashboard Spanish dictionary.
 * Merged from checklist HTML + live dashboard extras.
 */
(function (g) {
  g.AV_DASH_ES = {
  "INVENTORY": "INVENTARIO",
  "DOCUMENTS": "DOCUMENTOS",
  "PAYROLL": "NÓMINA",
  "TOOLS": "HERRAMIENTAS",
  "SALES": "VENTAS",
  "FINANCIALS": "FINANZAS",
  "REPORTS": "REPORTES",
  "Dashboard": "Panel",
  "Vehicles": "Vehículos",
  "Vehicles by Profit": "Vehículos por Ganancia",
  "Vehicles by Loss": "Vehículos por Pérdida",
  "Profit & Loss": "Ganancias y Pérdidas",
  "Expenses": "Gastos",
  "Paid Customers": "Clientes Pagados",
  "Customers": "Clientes",
  "Deal Jackets": "Carpetas de Venta",
  "Files & Storage": "Archivos y Almacenamiento",
  "Payroll & Commissions": "Nómina y Comisiones",
  "Sales Reps": "Vendedores",
  "Calendar": "Calendario",
  "Reports & Reminders": "Reportes y Recordatorios",
  "State Tax": "Impuesto Estatal",
  "CPA Portal Login": "Acceso Portal CPA",
  "+ Add Vehicle": "+ Agregar Vehículo",
  "+ Add Expense": "+ Agregar Gasto",
  "Scan VIN": "Escanear VIN",
  "Mark Sold": "Marcar Vendido",
  "+ Add Customer": "+ Agregar Cliente",
  "⋯ More": "⋯ Más",
  "Dealer Admin": "Admin del Concesionario",
  "Search vehicles, VIN, customers...": "Buscar vehículos, VIN, clientes...",
  "PAID CUSTOMERS": "CLIENTES PAGADOS",
  "PROFIT & LOSS": "GANANCIAS Y PÉRDIDAS",
  "VEHICLES BY PROFIT": "VEHÍCULOS POR GANANCIA",
  "VEHICLES BY LOSS": "VEHÍCULOS POR PÉRDIDA",
  "EXPENSES": "GASTOS",
  "PAYROLL & COMMISSIONS": "NÓMINA Y COMISIONES",
  "DEAL JACKETS": "CARPETAS DE VENTA",
  "SALES REPS": "VENDEDORES",
  "FLOORING BREAKDOWN": "DESGLOSE DE FINANCIAMIENTO",
  "Total Revenue": "Ingresos Totales",
  "Gross Profit": "Ganancia Bruta",
  "Net Profit": "Ganancia Neta",
  "Net Loss": "Pérdida Neta",
  "Total Expenses": "Gastos Totales",
  "Total Cost": "Costo Total",
  "Total Vehicle Cost": "Costo Total del Vehículo",
  "Vehicle Cost": "Costo del Vehículo",
  "Sold Price": "Precio de Venta",
  "Purchase Price": "Precio de Compra",
  "Vehicle Sold Price": "Precio de Venta del Vehículo",
  "Vehicle Purchase Price": "Precio de Compra del Vehículo",
  "Commission": "Comisión",
  "Commissions": "Comisiones",
  "Sales Commissions": "Comisiones de Venta",
  "Repairs": "Reparaciones",
  "Repairs / Expenses": "Reparaciones / Gastos",
  "Fees": "Cargos",
  "Flooring": "Financiamiento de Piso",
  "Flooring Cost": "Costo de Financiamiento",
  "Total Flooring Cost": "Costo Total de Financiamiento",
  "Add-Ons": "Extras",
  "Add-On Revenue": "Ingresos por Extras",
  "Sales Tax": "Impuesto de Venta",
  "Registration Fees": "Cargos de Registro",
  "Registration Fee ($)": "Cargo de Registro ($)",
  "Total Amount Collected": "Monto Total Cobrado",
  "Total Purchase Value": "Valor Total de Compra",
  "Average Purchase": "Compra Promedio",
  "Total Inventory": "Inventario Total",
  "Purchase Cost": "Costo de Compra",
  "Total Fees": "Cargos Totales",
  "Total Repairs": "Reparaciones Totales",
  "Upcoming Floored": "Financiados Próximos",
  "Vehicles at a Loss": "Vehículos en Pérdida",
  "Total Net Loss": "Pérdida Neta Total",
  "Average Loss": "Pérdida Promedio",
  "Average ROI %": "ROI Promedio %",
  "Total Profitable Vehicles": "Vehículos Rentables Totales",
  "Total Net Profit": "Ganancia Neta Total",
  "Sold This Month": "Vendidos Este Mes",
  "Titles": "Títulos",
  "Deals Closed": "Ventas Cerradas",
  "Total Sold Value": "Valor Total Vendido",
  "Avg ROI": "ROI Prom.",
  "Vehicles Floored": "Vehículos Financiados",
  "Flooring Fees Owed": "Cargos de Financiamiento Adeudados",
  "Owed to Flooring Co.": "Adeudado a la Financiera",
  "Coming Up for Payoff": "Próximos a Liquidar",
  "Total Payroll": "Nómina Total",
  "Wages & Salary": "Sueldos y Salarios",
  "Headcount": "Personal",
  "Team Payroll": "Nómina del Equipo",
  "Customer Directory": "Directorio de Clientes",
  "Revenue Allocation": "Distribución de Ingresos",
  "Profit & Loss Statement": "Estado de Ganancias y Pérdidas",
  "How Net Profit Was Calculated": "Cómo se Calculó la Ganancia Neta",
  "Where the Money Goes": "A Dónde Va el Dinero",
  "Where You're Losing": "Dónde Estás Perdiendo",
  "Rest of Inventory": "Resto del Inventario",
  "Other Paid Customers": "Otros Clientes Pagados",
  "Underwater Vehicles": "Vehículos en Números Rojos",
  "Floored Vehicles": "Vehículos Financiados",
  "All Sales Reps": "Todos los Vendedores",
  "Cost of Goods Sold": "Costo de Ventas",
  "Revenue": "Ingresos",
  "Operating Expenses": "Gastos Operativos",
  "Sale Information": "Información de Venta",
  "Customer Information": "Información del Cliente",
  "Cost Breakdown": "Desglose de Costos",
  "Sales Rep & Commission": "Vendedor y Comisión",
  "Add-On Upcharges": "Cargos por Extras",
  "Documents": "Documentos",
  "Deal Notes": "Notas de Venta",
  "Full Name": "Nombre Completo",
  "Cell Phone": "Teléfono Celular",
  "Email": "Correo",
  "Address": "Dirección",
  "Sale Date": "Fecha de Venta",
  "Deal Number": "Número de Venta",
  "State Sales Tax ($)": "Impuesto de Venta Estatal ($)",
  "Sold Price ($)": "Precio de Venta ($)",
  "Sales Rep": "Vendedor",
  "Commission %": "Comisión %",
  "Or Commission $": "O Comisión $",
  "Commission owed to rep": "Comisión adeudada al vendedor",
  "Save Deal & Mark Sold": "Guardar Venta y Marcar Vendido",
  "Choose another vehicle": "Elegir otro vehículo",
  "Back to Paid Customers": "Volver a Clientes Pagados",
  "Scan Document": "Escanear Documento",
  "Scan / Upload ID": "Escanear / Subir ID",
  "Purchase Agreement": "Contrato de Compra",
  "Title": "Título",
  "Odometer Statement": "Declaración de Odómetro",
  "Bill of Sale": "Factura de Venta",
  "Insurance": "Seguro",
  "Registration": "Registro",
  "Payment Method": "Método de Pago",
  "Category": "Categoría",
  "Amount": "Monto",
  "Due Date": "Fecha de Vencimiento",
  "Frequency": "Frecuencia",
  "Notes": "Notas",
  "Status": "Estado",
  "Paid": "Pagado",
  "Unpaid": "No Pagado",
  "Attach to vehicle": "Adjuntar a vehículo",
  "Add Expense": "Agregar Gasto",
  "Edit Expense": "Editar Gasto",
  "Employee": "Empleado",
  "Role": "Rol",
  "Pay Type": "Tipo de Pago",
  "Basis": "Base",
  "Earnings": "Ganancias",
  "Add Employee": "Agregar Empleado",
  "Edit Employee": "Editar Empleado",
  "Add Sales Rep": "Agregar Vendedor",
  "Salary": "Salario",
  "Hourly": "Por Hora",
  "Name": "Nombre",
  "Monthly Salary ($)": "Salario Mensual ($)",
  "Hourly Rate ($)": "Tarifa por Hora ($)",
  "Hours / Month": "Horas / Mes",
  "Commission Rate (% of gross)": "Tasa de Comisión (% del bruto)",
  "Customer": "Cliente",
  "Phone": "Teléfono",
  "Vehicle Purchased": "Vehículo Comprado",
  "Purchased": "Comprado",
  "Sale Price": "Precio de Venta",
  "Vehicle": "Vehículo",
  "Actions": "Acciones",
  "Days on Lot": "Días en el Lote",
  "Sales Rep ": "Vendedor ",
  "ROI %": "ROI %",
  "Gross": "Bruto",
  "Date": "Fecha",
  "Save": "Guardar",
  "Cancel": "Cancelar",
  "Delete": "Eliminar",
  "Remove": "Quitar",
  "Got it": "Entendido",
  "Exit": "Salir",
  "Save Rep": "Guardar Vendedor",
  "Print / Export": "Imprimir / Exportar",
  "Monthly": "Mensual",
  "Yearly": "Anual",
  "View Flooring Cost": "Ver Costo de Financiamiento",
  "Mark Paid Off": "Marcar Liquidado",
  "Top Sales Rep": "Mejor Vendedor",
  "Cars Sold": "Autos Vendidos",
  "Avg / Deal": "Prom. / Venta",
  "View details →": "Ver detalles →",
  "View deal jacket →": "Ver carpeta de venta →",
  "Appearance": "Apariencia",
  "Language": "Idioma",
  "Dark or light theme": "Tema oscuro o claro",
  "Settings": "Ajustes",
  "Numbers stay the same; only wording changes.": "Los números no cambian; solo cambia el texto.",
  "Acquisition & Cost Breakdown": "Adquisición y Desglose de Costos",
  "Vehicle Acquisition": "Adquisición del Vehículo",
  "Sale & Profit": "Venta y Ganancia",
  "+ Add Previous Sold Vehicle": "+ Agregar Vehículo Vendido Anteriormente",
  "Add Previous Sold Vehicle": "Agregar Vehículo Vendido Anteriormente",
  "Available": "Disponible",
  "All": "Todos",
  "Sold": "Vendido",
  "Sold Vehicles": "Vehículos Vendidos",
  "Sold Vehicles by Month": "Vehículos Vendidos por Mes",
  "Sort: Default": "Orden: Predeterminado",
  "Net Profit (high → low)": "Ganancia Neta (mayor → menor)",
  "ROI (high → low)": "ROI (mayor → menor)",
  "Days in Inventory (high → low)": "Días en Inventario (mayor → menor)",
  "Flooring Cost (high → low)": "Costo de Financiamiento (mayor → menor)",
  "Add Grid Lines": "Agregar Líneas de Cuadrícula",
  "Remove Grid Lines": "Quitar Líneas de Cuadrícula",
  "Vehicles by Month": "Vehículos por Mes",
  "Available Inventory": "Inventario Disponible",
  "All-In Vehicle Cost": "Costo Total del Vehículo",
  "Profit This Month": "Ganancia Este Mes",
  "available inventory": "inventario disponible",
  "all vehicles": "todos los vehículos",
  "sold vehicles": "vehículos vendidos",
  "Costs ·": "Costos ·",
  "spent on current stock": "gastado en stock actual",
  "recon + parts": "recon + partes",
  "collected this period": "cobrado este periodo",
  "owed to reps": "adeudado a vendedores",
  "all-in on current stock": "total en stock actual",
  "net, sold this month": "neto, vendido este mes",
  "Search vehicles, VIN, or rep…": "Buscar vehículos, VIN o vendedor…",
  "Add Vehicle": "Agregar Vehículo",
  "Scan VIN number": "Escanear número VIN",
  "Or paste / type the VIN": "O pegue / escriba el VIN",
  "Add without VIN number": "Agregar sin número VIN",
  "Add with VIN number": "Agregar con número VIN",
  "Year": "Año",
  "Make": "Marca",
  "Model": "Modelo",
  "Purchase Date": "Fecha de Compra",
  "Dates": "Fechas",
  "Acquisition & Costs": "Adquisición y Costos",
  "Sale": "Venta",
  "Purchase Price ($)": "Precio de Compra ($)",
  "Auction Fees ($)": "Cargos de Subasta ($)",
  "Auction / Doc Fees ($)": "Cargos de Subasta / Doc ($)",
  "Repairs / Recon ($)": "Reparaciones / Recon ($)",
  "Other Expenses ($)": "Otros Gastos ($)",
  "Flooring Cost ($)": "Costo de Financiamiento ($)",
  "Purchase Location": "Lugar de Compra",
  "Sale Price ($)": "Precio de Venta ($)",
  "Sales Tax Collected ($)": "Impuesto de Venta Cobrado ($)",
  "Registration Fees ($)": "Cargos de Registro ($)",
  "Commission ($)": "Comisión ($)",
  "Add Flooring Rate": "Agregar Tasa de Financiamiento",
  "Add Vehicle to Inventory": "Agregar Vehículo al Inventario",
  "Save to Sold Vehicles": "Guardar en Vehículos Vendidos",
  "+ Add add-on": "+ Agregar extra",
  "Leave blank for none": "Deje en blanco si no aplica",
  "Blank = auto-calculate": "En blanco = cálculo automático",
  "Pick an auction or type your own": "Elija una subasta o escriba la suya",
  "Is the title present for this vehicle?": "¿Está presente el título de este vehículo?",
  "Yes, title is in": "Sí, el título está",
  "No, not yet": "No, todavía no",
  "Save this vehicle without a VIN?": "¿Guardar este vehículo sin VIN?",
  "Yes, save without VIN": "Sí, guardar sin VIN",
  "No, I'll add it": "No, lo agregaré",
  "17-digit VIN…": "VIN de 17 dígitos…",
  "Payment Settings": "Configuración de Pagos",
  "Contact Support": "Contactar Soporte",
  "Owner Login": "Acceso del Dueño",
  "Review Notes": "Notas de Revisión",
  "Log Out": "Cerrar Sesión",
  "Financials": "Finanzas",
  "Payroll": "Nómina",
  "Tools": "Herramientas",
  "CPA Tools": "Herramientas CPA",
  "Inventory": "Inventario",
  "SALES TAX": "IMPUESTO DE VENTA",
  "Sales Tax Filing Schedule": "Calendario de Declaración de Impuestos",
  "Quarterly Filing": "Declaración Trimestral",
  "Monthly Filing": "Declaración Mensual",
  "Semi-Annual Filing": "Declaración Semestral",
  "Annual Filing": "Declaración Anual",
  "Mark as Filed": "Marcar como Declarado",
  "Edit Filing Schedule": "Editar Calendario",
  "Total Sales Tax": "Impuesto de Venta Total",
  "Taxable Sales": "Ventas Gravables",
  "total sold value": "valor total vendido",
  "in this period": "en este periodo",
  "Next Filing": "Próxima Declaración",
  "set a due date": "fije una fecha de vencimiento",
  "Sales Tax by Vehicle": "Impuesto de Venta por Vehículo",
  "Tax by Month": "Impuesto por Mes",
  "Show Quarterly Filings": "Mostrar Declaraciones Trimestrales",
  "Show Monthly Filings": "Ver Declaraciones Mensuales",
  "Show Semi-Annual Filings": "Ver Declaraciones Semestrales",
  "Show Annual Filings": "Ver Declaraciones Anuales",
  "Show Flat List": "Ver Lista Simple",
  "Filing History": "Historial de Declaraciones",
  "Export CSV": "Exportar CSV",
  "Sold Date": "Fecha de Venta",
  "Rate": "Tasa",
  "SOLD VEHICLES": "VEHÍCULOS VENDIDOS",
  "Sold History": "Historial de Ventas",
  "Vehicle History": "Historial del Vehículo",
  "PAYMENT SETTINGS": "AJUSTES DE PAGO",
  "ACCOUNT": "CUENTA",
  "Current Plan": "Plan Actual",
  "Upgrade Plan": "Mejorar Plan",
  "Update Payment Method": "Actualizar Método de Pago",
  "Make a Payment": "Hacer un Pago",
  "Add Payments to Expenses Automatically": "Agregar Pagos a Gastos Automáticamente",
  "Signed Agreement": "Acuerdo Firmado",
  "Billing History": "Historial de Facturación",
  "CALENDAR": "CALENDARIO",
  "View Flooring Calendar": "Ver Calendario de Financiamiento",
  "View Sales Calendar": "Ver Calendario de Ventas",
  "Sales Calendar": "Calendario de Ventas",
  "Flooring Calendar": "Calendario de Financiamiento",
  "How much did it sell for? ($)": "¿En cuánto se vendió? ($)",
  "The Sale": "La Venta",
  "Deal Type / Status": "Tipo de Venta / Estado",
  "Arbitration": "Arbitraje",
  "Sold at a Loss": "Vendido con Pérdida",
  "Wholesale": "Mayoreo",
  "Out of State Sale": "Venta Fuera del Estado",
  "Financing": "Financiamiento",
  "optional": "opcional",
  "Net Check ($)": "Cheque Neto ($)",
  "Collected for State": "Cobrado para el Estado",
  "pass-through": "traspaso",
  "Your profit on this deal": "Tu ganancia en esta venta",
  "click any figure to edit": "haga clic en cualquier cifra para editar",
  "Standard sale by default. Pick Arbitration, Sold at a Loss, Wholesale, or Out of State to open its details.": "Venta estándar por defecto. Elija Arbitraje, Vendido con Pérdida, Mayoreo o Fuera del Estado para abrir sus detalles.",
  "Your Name": "Su Nombre",
  "Topic": "Tema",
  "Subject": "Asunto",
  "Priority": "Prioridad",
  "Low": "Baja",
  "Normal": "Normal",
  "Urgent": "Urgente",
  "Message": "Mensaje",
  "Send Message": "Enviar Mensaje",
  "Done": "Listo",
  "Technical issue": "Problema técnico",
  "Billing & payments": "Facturación y pagos",
  "Feature request": "Solicitud de función",
  "Bug report": "Reporte de error",
  "Account / login": "Cuenta / acceso",
  "Titles Present": "Títulos Presentes",
  "in-stock · click to filter": "en stock · clic para filtrar",
  "All Vehicles": "Todos los Vehículos",
  "By Profit": "Por Ganancia",
  "By Loss": "Por Pérdida",
  "Vehicle Sales": "Ventas de Vehículos",
  "Add-On & Upcharge Revenue": "Ingresos por Extras y Recargos",
  "Auction & Title Fees": "Cargos de Subasta y Título",
  "Reconditioning & Repairs": "Reacondicionamiento y Reparaciones",
  "Floor-Plan (Flooring)": "Plan de Piso (Financiamiento)",
  "Vehicle Expenses": "Gastos de Vehículos",
  "Add-On Cost": "Costo de Extras",
  "Total COGS": "Costo de Ventas Total",
  "Sales Commissions & Payroll": "Comisiones de Venta y Nómina",
  "Recurring Expenses": "Gastos Recurrentes",
  "Dealership Expenses": "Gastos del Concesionario",
  "Total Operating Expenses": "Gastos Operativos Totales",
  "view": "ver",
  "view all →": "ver todo →",
  "Sold / Ask": "Vendido / Pedido",
  "Sun": "Dom",
  "Mon": "Lun",
  "Tue": "Mar",
  "Wed": "Mié",
  "Thu": "Jue",
  "Fri": "Vie",
  "Sat": "Sáb",
  "January": "Enero",
  "February": "Febrero",
  "March": "Marzo",
  "April": "Abril",
  "May": "Mayo",
  "June": "Junio",
  "July": "Julio",
  "August": "Agosto",
  "September": "Septiembre",
  "October": "Octubre",
  "November": "Noviembre",
  "December": "Diciembre",
  "Jan": "Ene",
  "Apr": "Abr",
  "Aug": "Ago",
  "Dec": "Dic",
  "Search vehicles, VIN, customers, jackets…": "Buscar vehículos, VIN, clientes, jackets…",
  "Sold Value": "Valor Vendido",
  "units sold": "unidades vendidas",
  "units moved": "unidades movidas",
  "This Month": "Este Mes",
  "Total Vehicles": "Vehículos Totales",
  "on the lot now": "en el lote ahora",
  "Flooring rate system": "Sistema de tasa de financiamiento",
  "Add Flooring Rate to System": "Agregar Tasa de Financiamiento al Sistema",
  "Browse sold history": "Explorar historial de ventas",
  "vehicles on lot": "vehículos en el lote",
  "vehicles in current inventory": "vehículos en inventario actual",
  "Profit Calculator": "Calculadora de Ganancia",
  "Set Status…": "Definir Estado…",
  "Open Deal Jacket →": "Abrir Carpeta de Venta →",
  "Fill in the sale below — your profit updates live as you type.": "Completa la venta abajo — tu ganancia se actualiza al escribir.",
  "No commission · $0": "Sin comisión · $0",
  "You're in at": "Estás invertido en",
  "If you sell for": "Si vendes por",
  "Projected profit": "Ganancia proyectada",
  "Purchase price": "Precio de compra",
  "Other expenses": "Otros gastos",
  "No itemized costs yet": "Aún no hay costos desglosados",
  "Enter a target sale price to see your projected profit.": "Ingresa un precio de venta para ver la ganancia proyectada.",
  "Enter a sale price of $0 or more.": "Ingresa un precio de venta de $0 o más.",
  "Bright mode": "Modo claro",
  "Dark / Bright theme": "Tema oscuro / claro",
  "Switch to bright mode": "Cambiar a modo claro",
  "Switch to dark mode": "Cambiar a modo oscuro",
  "Flooring Rate System": "Sistema de Tasa de Financiamiento",
  "Floor-plan interest, tracked per vehicle": "Interés del plan de piso, rastreado por vehículo",
  "Remove From All": "Quitar de Todos",
  "Sort": "Ordenar",
  "Add Previous Sold": "Agregar Vendido Anterior",
  "Success": "Éxito",
  "Warning": "Advertencia",
  "Something went wrong": "Algo salió mal",
  "Working": "Trabajando",
  "Notice": "Aviso",
  "Please wait": "Por favor espera",
  "Saving…": "Guardando…",
  "Deal saved": "Venta guardada",
  "Deal jacket created": "Carpeta de venta creada",
  "Repair saved": "Reparación guardada",
  "Repair removed": "Reparación eliminada",
  "Failed to save repair": "No se pudo guardar la reparación",
  "Failed to delete repair": "No se pudo eliminar la reparación",
  "Flooring rates cannot be negative": "Las tasas de financiamiento no pueden ser negativas",
  "Description and price are required": "Se requieren descripción y precio",
  "Purchase date updated": "Fecha de compra actualizada",
  "Saved": "Guardado",
  "Save failed": "Error al guardar",
  "Failed to save deal": "No se pudo guardar la venta",
  "Failed to save rep": "No se pudo guardar el vendedor",
  "Close": "Cerrar",
  "Click Add Repair (or Update Repair) first, then Save": "Haz clic en Agregar Reparación (o Actualizar) primero, luego Guardar",
  "Welcome back": "Bienvenido de nuevo",
  "Welcome back,": "Bienvenido de nuevo,",
  "Welcome back, ": "Bienvenido de nuevo, ",
  ". Here is your month at a glance.": ". Aquí tienes tu mes de un vistazo.",
  "Vehicles Sold": "Vehículos Vendidos",
  "this month": "este mes",
  "before costs": "antes de costos",
  "after all costs": "después de todos los costos",
  "Owed to Reps": "Adeudado a Vendedores",
  "commission this month": "comisión este mes",
  "Total Invested": "Total Invertido",
  "in vehicles sold": "en vehículos vendidos",
  "sold vehicles": "vehículos vendidos",
  "gross sales": "ventas brutas",
  "across deals": "en todas las ventas",
  "in this period": "en este periodo",
  "Accountant full name": "Nombre completo del contador",
  "Add sticky note": "Agregar nota adhesiva",
  "Additional notes": "Notas adicionales",
  "Any notes about this funding check…": "Notas sobre este cheque de financiamiento…",
  "Ask Jenna anything...": "Pregúntale lo que quieras a Jenna...",
  "Ask Jenna — drag to move": "Pregunta a Jenna — arrastra para mover",
  "Attach a vehicle": "Adjuntar un vehículo",
  "Attached Vehicle": "Vehículo Adjunto",
  "Back to auto-calculated": "Volver al cálculo automático",
  "Brief summary — e.g. Can't mark a vehicle sold": "Resumen breve — ej. No puedo marcar un vehículo vendido",
  "Buyer / dealer name": "Nombre del comprador / concesionario",
  "Calculated after an actual sale price is entered": "Calculado después de ingresar un precio de venta real",
  "Calculator": "Calculadora",
  "Change number color": "Cambiar color del número",
  "Choose which vehicles the spreadsheet shows": "Elija qué vehículos muestra la hoja",
  "City": "Ciudad",
  "Clear net check and use sold-price profit": "Borrar cheque neto y usar ganancia por precio vendido",
  "Click for flooring": "Clic para financiamiento",
  "Click for repairs": "Clic para reparaciones",
  "Click to change the purchase date": "Clic para cambiar la fecha de compra",
  "Click to collapse this column": "Clic para contraer esta columna",
  "Click to cycle: titles present → titles missing → all": "Clic para alternar: títulos presentes → faltantes → todos",
  "Click to edit": "Clic para editar",
  "Click to edit attached expenses": "Clic para editar gastos adjuntos",
  "Click to edit purchase date": "Clic para editar fecha de compra",
  "Click to edit rep & commission": "Clic para editar vendedor y comisión",
  "Click to edit repair items": "Clic para editar reparaciones",
  "Click to enter actual net check from finance": "Clic para ingresar cheque neto real del financiamiento",
  "Click to minimize / expand": "Clic para minimizar / expandir",
  "Click to see vehicles due for flooring payoff": "Clic para ver vehículos próximos a liquidar",
  "Click to set your target sale price": "Clic para fijar su precio objetivo de venta",
  "Click to view present titles": "Clic para ver títulos presentes",
  "Click to view repairs & attached expenses": "Clic para ver reparaciones y gastos adjuntos",
  "Collapse sidebar": "Contraer barra lateral",
  "Contact name": "Nombre de contacto",
  "Cost of available inventory": "Costo del inventario disponible",
  "Create a strong password": "Cree una contraseña segura",
  "Current password": "Contraseña actual",
  "Customer full name": "Nombre completo del cliente",
  "Dark / Bright": "Oscuro / Claro",
  "Days in Inventory": "Días en Inventario",
  "Dealer #": "N.º de concesionario",
  "Dealership / business name": "Nombre del concesionario / negocio",
  "Dealership Expense": "Gasto del Concesionario",
  "Dealership name": "Nombre del concesionario",
  "Description": "Descripción",
  "Dismiss": "Descartar",
  "Edit": "Editar",
  "Edit rate": "Editar tasa",
  "English / Español": "English / Español",
  "Enter lender name": "Ingrese nombre del prestamista",
  "Filter by expense or note...": "Filtrar por gasto o nota...",
  "Filter by expense, vehicle, or note...": "Filtrar por gasto, vehículo o nota...",
  "Flat dollar amount per deal": "Monto fijo en dólares por venta",
  "Full Contact on File": "Contacto Completo en Archivo",
  "Full legal name": "Nombre legal completo",
  "Full name": "Nombre completo",
  "Generate a unique DL-##### deal number": "Generar un número de venta DL-##### único",
  "Inventory Cost": "Costo de Inventario",
  "Language / Idioma — switch to Español": "Language / Idioma — cambiar a Español",
  "Leads": "Prospectos",
  "Log in as this rep": "Iniciar sesión como este vendedor",
  "Look up VIN or vehicle...": "Buscar VIN o vehículo...",
  "Manheim, ADESA, dealer trade, private…": "Manheim, ADESA, intercambio, particular…",
  "Manheim, ADESA, etc.": "Manheim, ADESA, etc.",
  "Mark all as read": "Marcar todo como leído",
  "Mark vehicle as sold to enable Registration Fees": "Marque el vehículo vendido para habilitar cargos de registro",
  "Monthly Impact": "Impacto Mensual",
  "Net Salary": "Salario Neto",
  "New message": "Nuevo mensaje",
  "Next month": "Mes siguiente",
  "Next year": "Año siguiente",
  "Notes about this vehicle…": "Notas sobre este vehículo…",
  "Notes for this day…": "Notas para este día…",
  "Notifications": "Notificaciones",
  "Open in Flooring Breakdown": "Abrir en Desglose de Financiamiento",
  "Open this expense": "Abrir este gasto",
  "Open vehicle — this cost is in its P&L": "Abrir vehículo — este costo está en su G&P",
  "Optional — vendor, reference #, context": "Opcional — proveedor, referencia #, contexto",
  "Paid This Month": "Pagado Este Mes",
  "Paid This Year": "Pagado Este Año",
  "Password": "Contraseña",
  "Paste or type a VIN to attach": "Pegue o escriba un VIN para adjuntar",
  "Pay Breakdown": "Desglose de Pago",
  "Pay Schedule": "Calendario de Pago",
  "Payment History": "Historial de Pagos",
  "Payroll & Commission": "Nómina y Comisión",
  "Percentage of gross": "Porcentaje del bruto",
  "Pick date": "Elegir fecha",
  "Previous month": "Mes anterior",
  "Previous year": "Año anterior",
  "ROI": "ROI",
  "Re-enter new password": "Vuelva a ingresar la contraseña",
  "Reassign sales rep": "Reasignar vendedor",
  "Receipt": "Recibo",
  "Recurring Expense": "Gasto Recurrente",
  "Remove document": "Eliminar documento",
  "Revert to previous value": "Revertir al valor anterior",
  "Revert to your previous value": "Revertir a su valor anterior",
  "Sales tax collected this filing period — click for the full breakdown": "Impuesto cobrado en este periodo — clic para ver desglose completo",
  "Scan a document": "Escanear un documento",
  "Search conversations": "Buscar conversaciones",
  "Search customers, phone, email, VIN…": "Buscar clientes, teléfono, correo, VIN…",
  "Search leads by name, phone, email…": "Buscar prospectos por nombre, teléfono, correo…",
  "Search user, dealership, or state…": "Buscar usuario, concesionario o estado…",
  "Search vehicle or VIN…": "Buscar vehículo o VIN…",
  "Select a conversation to start messaging": "Seleccione una conversación para enviar mensajes",
  "Select or type a rep…": "Seleccione o escriba un vendedor…",
  "Send": "Enviar",
  "Show All-In + Flooring": "Mostrar Total + Financiamiento",
  "Show Flooring Age": "Mostrar Antigüedad de Financiamiento",
  "Show Flooring Cost": "Mostrar Costo de Financiamiento",
  "Show Potential Profit": "Mostrar Ganancia Potencial",
  "Show all deal jackets, or filter to a single month": "Mostrar todas las carpetas o filtrar por un mes",
  "Show all expenses": "Mostrar todos los gastos",
  "Stop": "Detener",
  "Stop or edit recurring expenses": "Detener o editar gastos recurrentes",
  "Street address": "Dirección",
  "Street, City, State ZIP": "Calle, Ciudad, Estado CP",
  "Tell us what's going on and how we can help…": "Cuéntenos qué ocurre y cómo podemos ayudar…",
  "Total Gross": "Bruto Total",
  "Total Net": "Neto Total",
  "Total Sales": "Ventas Totales",
  "Trade-in details, financing terms, promises made, follow-ups…": "Detalles de permuta, financiamiento, promesas, seguimientos…",
  "Type notes about this vehicle…": "Escriba notas sobre este vehículo…",
  "Type notes for this day…": "Escriba notas para este día…",
  "Type your own description": "Escriba su propia descripción",
  "Update vehicle status": "Actualizar estado del vehículo",
  "Users & access": "Usuarios y acceso",
  "Vehicle Expense": "Gasto del Vehículo",
  "View": "Ver",
  "View dealership expenses only": "Ver solo gastos del concesionario",
  "View every operating expense in this period, including recurring": "Ver todos los gastos operativos del periodo, incluidos recurrentes",
  "View payroll & commission only": "Ver solo nómina y comisión",
  "View receipt": "Ver recibo",
  "View recurring expenses only": "Ver solo gastos recurrentes",
  "View vehicle expenses only": "Ver solo gastos del vehículo",
  "What are they interested in?": "¿En qué están interesados?",
  "Write a review note or question for the dealer...": "Escriba una nota o pregunta para el concesionario...",
  "Write notes for this day...": "Escriba notas para este día...",
  "Your name": "Su nombre",
  "accrued interest to date": "interés acumulado a la fecha",
  "all-in cost": "costo total",
  "annualized": "anualizado",
  "auto": "automático",
  "before commission": "antes de comisión",
  "billing cycle": "ciclo de facturación",
  "click to view present titles": "clic para ver títulos presentes",
  "due soon or overdue": "próximo a vencer o vencido",
  "earned from deals": "ganado en ventas",
  "earned this period": "ganado en este periodo",
  "expense total": "total de gastos",
  "floored 30+ days · pay off soon": "financiado 30+ días · liquidar pronto",
  "greater of base / commission": "mayor entre base / comisión",
  "loading…": "cargando…",
  "on the floor plan": "en el plan de piso",
  "on the team": "en el equipo",
  "per customer": "por cliente",
  "phone & email captured": "teléfono y correo registrados",
  "principal + fees to clear": "capital + cargos por liquidar",
  "return on cost": "retorno sobre costo",
  "sold value": "valor vendido",
  "sold − purchase": "vendido − compra",
  "staff (hourly + salary)": "personal (por hora + salario)",
  "sum of what they paid": "suma de lo que pagaron",
  "this period": "este periodo",
  "to customer": "al cliente",
  "total sale price": "precio total de venta",
  "vehicle sales + add-ons": "ventas de vehículos + extras",
  "vehicles sold to buyers": "vehículos vendidos a compradores",
  "— gross margin": "— margen bruto",
  "— net margin": "— margen neto",
  "Profitable Sales": "Ventas Rentables",
  "Loss Sales": "Ventas con Pérdida",
  "My Leads": "Mis Prospectos",
  "Customer Leads": "Prospectos de Clientes",
  "Loading inventory…": "Cargando inventario…",
  "Loading sales…": "Cargando ventas…",
  "Has sales activity": "Tiene actividad de ventas",
  "No sales this month": "Sin ventas este mes",
  "And happy birthday to you! 🎉": "¡Y feliz cumpleaños para usted! 🎉",
  "You're doing well this month.": "Le va bien este mes.",
  "Looks like this'll be a profitable month.": "Parece que será un mes rentable.",
  "Let's keep an eye on the margins this month.": "Vigilemos los márgenes este mes.",
  "Let me know if there's anything I can help you with.": "Avíseme si puedo ayudarle en algo.",
  "Full Year": "Año Completo",
  "Financials · this vs last": "Finanzas · este vs anterior",
  "Compare": "Comparar",
  "vs last month": "vs mes anterior",
  "vs last year": "vs año anterior",
  "No vehicles in inventory yet.": "Aún no hay vehículos en inventario.",
  "No repair entries yet. Add the first one below.": "Aún no hay reparaciones. Agregue la primera abajo.",
  "Enter a description, then click + Add Repair or Save.": "Ingrese una descripción, luego + Agregar Reparación o Guardar.",
  "Update Repair": "Actualizar Reparación",
  "+ Add Repair": "+ Agregar Reparación",
  "Failed to load inventory. Check your connection and try again.": "No se pudo cargar el inventario. Revise su conexión e intente de nuevo.",
  "in active inventory": "en inventario activo",
  "Present": "Presente",
  "Missing": "Faltante",
  "Pending": "Pendiente",
  "Active": "Activo",
  "In Stock": "En Stock",
  "Converted": "Convertido",
  "Lost": "Perdido",
  "New": "Nuevo",
  "Contacted": "Contactado",
  "Qualified": "Calificado",
  "Standard": "Estándar",
  "One-time": "Única vez",
  "Recurring": "Recurrente",
  "Messages": "Mensajes",
  "Global Search": "Búsqueda Global",
  "Change Password": "Cambiar Contraseña",
  "Terms of Service": "Términos de Servicio",
  "Privacy Policy": "Política de Privacidad",
  "You're up ": "Subió ",
  "You're down ": "Bajó ",
  "% from last month.": "% respecto al mes anterior.",
  "&mdash; gross margin": "— margen bruto",
  "&mdash; net margin": "— margen neto",
  "Optional &mdash; vendor, reference #, context": "Opcional — proveedor, referencia #, contexto",
  "Notes for this day\u2026": "Notas para este día…",
  "Type notes for this day\u2026": "Escriba notas para este día…",
  "Manheim, ADESA, dealer trade, private\u2026": "Manheim, ADESA, intercambio, particular…",
  "Wholesale CRM": "CRM Mayorista",
  "Sales Rep Login": "Acceso Vendedor",
  "Add Sales Rep Login": "Agregar Acceso de Vendedor",
  "Nothing found for": "No se encontró nada para",
  "Try VIN, stock #, customer, or jacket number.":
    "Pruebe VIN, n.º de stock, cliente o número de carpeta.",
  "Payment past due — ": "Pago vencido — ",
  "Due ": "Vence ",
  day: "día",
  days: "días",
  late: "de retraso",
  "Expires ": "Vence ",
  "payments are added to Expenses as": "los pagos se agregan a Gastos como",
  "under Dealership Expense → Subscriptions.":
    "bajo Gasto del Concesionario → Suscripciones.",
  "you'll get an email 3 days before each billing date.":
    "recibirá un correo 3 días antes de cada fecha de facturación.",
  "Off — no 3-day reminder emails (billing-day notice still sends).":
    "Desactivado — sin recordatorios de 3 días (el aviso del día de facturación sí se envía).",
  "vehicle sold": "vehículo vendido",
  "vehicles sold": "vehículos vendidos",
  "across all vehicles": "en todos los vehículos",
  "all-in, all vehicles": "total, todos los vehículos",
  "on cars sold": "en autos vendidos",
  "all-in, cars sold": "total, autos vendidos",
  "collected ": "cobrado ",
  "Sales activity, appointments, and notes — one day at a time.":
    "Actividad de ventas, citas y notas — día a día.",
  "No vehicles on the floor plan right now.":
    "No hay vehículos en el plan de piso ahora.",
  "Floored (purchased)": "Financiado (comprado)",
  "Payoff due": "Liquidación pendiente",
  "Paid off": "Liquidado",
  Today: "Hoy",
  "in stock · total value all-in": "en stock · valor total incluido",
  " of ": " de ",
  " car": " auto",
  " cars": " autos",
  "Costs · ": "Costos · ",
  "VIEW SALES INVENTORY": "VER INVENTARIO DE VENTAS",
  "View Sales Inventory": "Ver Inventario de Ventas",
  "Type at least 2 characters to search vehicles, VINs, customers, deal jackets, and expenses.": "Escriba al menos 2 caracteres para buscar vehículos, VIN, clientes, carpetas de venta y gastos.",
  "No matches": "Sin coincidencias",
  "Search failed": "Búsqueda fallida",
  "Please try again.": "Inténtelo de nuevo.",
  "Customers & Leads": "Clientes y Prospectos",
  "Customers &amp; Leads": "Clientes y Prospectos",
  "No conversations yet. Start a new message!": "Aún no hay conversaciones. ¡Inicie un mensaje nuevo!",
  "No conversations match your search.": "Ninguna conversación coincide con su búsqueda.",
  "Your messages": "Sus mensajes",
  "Select a conversation or start a new one.": "Seleccione una conversación o inicie una nueva.",
  "New Message": "Nuevo Mensaje",
  "No contacts found.": "No se encontraron contactos.",
  "Type a message": "Escriba un mensaje",
  "TEAM": "EQUIPO",
  "MESSAGES": "MENSAJES",
  "All caught up. No reminders right now.": "Todo al día. No hay recordatorios por ahora.",
  "Every closed deal is filed here with its paperwork and customer record.": "Cada venta cerrada se archiva aquí con su documentación y el registro del cliente.",
  "No deals closed yet. Click “New Deal / Mark Sold” to create one.": "Aún no hay ventas cerradas. Haga clic en “Nueva Venta / Marcar Vendido” para crear una.",
  "New Deal / Mark Sold": "Nueva Venta / Marcar Vendido",
  " Titles In / Not In": " Títulos En / Fuera",
  "Titles In / Not In": "Títulos En / Fuera",
  "All Deal Jackets": "Todas las Carpetas",
  "Deal Jackets by Month": "Carpetas por Mes",
  "No deals closed in ": "No hay ventas cerradas en ",
  " units sold + add-ons": " unidades vendidas + extras",
  " unit sold + add-ons": " unidad vendida + extras",
  "gross margin": "margen bruto",
  "net margin": "margen neto",
  "operating expenses (excludes COGS) ·": "gastos operativos (excluye COGS) ·",
  "Vehicle-Attached Expenses": "Gastos Adjuntados al Vehículo",
  "Less: Sales Commissions (Payroll)": "Menos: Comisiones de Venta (Nómina)",
  "Less: Operating Expenses": "Menos: Gastos Operativos",
  "No vehicles sold in this period. Sales data will appear here once deals are completed and marked as sold.": "No hay vehículos vendidos en este periodo. Los datos de ventas aparecerán aquí cuando se completen y marquen como vendidos.",
  "Memo — outside the P&L:": "Memo — fuera del G&P:",
  "Sales tax & registration collected for the state (pass-through, not income): ": "Impuesto y registro cobrados para el estado (traspaso, no ingreso): ",
  "Recurring expenses auto-carry into each month's Operating Expenses until edited or deleted. Run-rate: ": "Los gastos recurrentes se trasladan automáticamente a Gastos Operativos cada mes hasta editarlos o eliminarlos. Ritmo: ",
  "/mo": "/mes",
  "Where every dollar goes": "A dónde va cada dólar",
  "Gross profit is what's left after the cost of the vehicles (COGS). From there we subtract the commissions paid to your sales reps and all dealership overhead (rent, utilities, marketing, etc.). What remains is your true bottom-line net profit.": "La ganancia bruta es lo que queda después del costo de los vehículos (COGS). De ahí restamos las comisiones de sus vendedores y todos los gastos generales del concesionario (renta, servicios, marketing, etc.). Lo que queda es su verdadera ganancia neta.",
  "Vehicle Cost (COGS)": "Costo del Vehículo (COGS)",
  "vehicles sold": "vehículos vendidos",
  "No leads yet. Add a lead to start tracking potential buyers.": "Aún no hay prospectos. Agregue uno para empezar a rastrear compradores potenciales.",
  "No leads yet. Click <b>+ Add Lead</b> to log a potential customer’s name, phone, and email.": "Aún no hay prospectos. Haga clic en <b>+ Agregar Prospecto</b> para registrar nombre, teléfono y correo.",
  "No leads yet. Click <b>+ Add Lead</b> to log a potential customer's name, phone, and email.": "Aún no hay prospectos. Haga clic en <b>+ Agregar Prospecto</b> para registrar nombre, teléfono y correo.",
  "+ Add Lead": "+ Agregar Prospecto",
  "No sales yet": "Aún no hay ventas",
  "Close a deal to crown your top rep.": "Cierre una venta para coronar a su mejor vendedor.",
  " reps on the team": " vendedores en el equipo",
  " rep on the team": " vendedor en el equipo",
  "For vehicles you sold before joining AutoVault. This saves straight into Sold Vehicles and updates every report, P&L and KPI as if it had been sold here.": "Para vehículos que vendió antes de unirse a AutoVault. Se guarda directo en Vehículos Vendidos y actualiza cada reporte, G&P y KPI como si se hubiera vendido aquí.",
  "before": "antes",
  "This keeps track of which sold-vehicle titles you have in hand.": "Esto lleva el control de qué títulos de vehículos vendidos tiene en mano.",
  "This keeps track of which titles you have in hand.": "Esto lleva el control de qué títulos tiene en mano.",
  "No flooring plan is set. Configure it in Flooring Cost first — it will not be added automatically.": "No hay plan de financiamiento. Configúrelo primero en Costo de Financiamiento — no se agregará automáticamente.",
  "Backdate this for vehicles bought in a previous month.": "Antedate esto para vehículos comprados en un mes anterior.",
  "Where you bought it — pick an auction or type your own.": "Dónde lo compró — elija una subasta o escriba la suya.",
  "Today": "Hoy",
  "Floored (purchased)": "Financiado (comprado)",
  "Payoff due": "Liquidación pendiente",
  "Paid off": "Liquidado",
  "Select a day to see its sales and write appointments or notes.": "Seleccione un día para ver sus ventas y escribir citas o notas.",
  "Click a day to add flooring notes for it.": "Haga clic en un día para agregar notas de financiamiento.",
  "Floored this day": "Financiados este día",
  "— your plan, billing, and payment method": "— su plan, facturación y método de pago",
  "Billing cycle": "Ciclo de facturación",
  "Next charge": "Próximo cargo",
  "Includes": "Incluye",
  "Upgrade plan": "Mejorar plan",
  "Amount due": "Monto adeudado",
  "Expense logging": "Registro de gastos",
  "Update payment method": "Actualizar método de pago",
  "Make a payment": "Hacer un pago",
  "Make payment": "Hacer pago",
  "Add payments to Expenses automatically": "Agregar pagos a Gastos automáticamente",
  "When on, every subscription payment is logged in your Expenses section under Dealership Expense / Subscriptions — so your books stay current without re-typing it.": "Cuando está activo, cada pago de suscripción se registra en Gastos bajo Gasto del Concesionario / Suscripciones — así sus libros se mantienen al día sin volver a escribirlo.",
  "When on, every subscription payment is logged in your Gastos section under Dealership Expense / Subscriptions — so your books stay current without re-typing it.": "Cuando está activo, cada pago de suscripción se registra en Gastos bajo Gasto del Concesionario / Suscripciones — así sus libros se mantienen al día sin volver a escribirlo.",
  "Notify me 3 days before billing": "Avisarme 3 días antes de la facturación",
  "NOTIFY ME 3 DAYS BEFORE BILLING": "AVISARME 3 DÍAS ANTES DE LA FACTURACIÓN",
  "When on, AutoVault emails you 3 days before each charge so you can confirm the card on file. A separate email always sends on the billing date itself.": "Cuando está activo, AutoVault le envía un correo 3 días antes de cada cargo para confirmar la tarjeta. Un correo aparte siempre se envía el día de facturación.",
  "Signed by": "Firmado por",
  "SIGNED BY": "FIRMADO POR",
  "DEALERSHIP": "CONCESIONARIO",
  "VERSION": "VERSIÓN",
  "ACCEPTED": "ACEPTADO",
  "Electronic Signature": "Firma Electrónica",
  "ELECTRONIC SIGNATURE": "FIRMA ELECTRÓNICA",
  "No payments yet.": "Aún no hay pagos.",
  "Billing not linked": "Facturación no vinculada",
  "Billing not linked; contact support.": "Facturación no vinculada; contacte a soporte.",
  "Contact support to connect Stripe.": "Contacte a soporte para conectar Stripe.",
  "Unlinked": "No vinculado",
  "UNLINKED": "NO VINCULADO",
  "Past due": "Vencido",
  "Past due since": "Vencido desde",
  "Connect billing to manage your payment method.": "Conecte la facturación para administrar su método de pago.",
  "Off — payments are not written to your Expenses section.": "Desactivado — los pagos no se escriben en Gastos.",
  "On — you'll get an email 3 days before each billing date.": "Activado — recibirá un correo 3 días antes de cada fecha de facturación.",
  "Your account is up to date": "Su cuenta está al día",
  "Next charge of ": "Próximo cargo de ",
  " on ": " el ",
  "Pay now to keep your account active.": "Pague ahora para mantener su cuenta activa.",
  "No card on file. Update your payment method to add one.": "No hay tarjeta registrada. Actualice el método de pago para agregar una.",
  "No card on file yet.": "Aún no hay tarjeta registrada.",
  "Choose a Plan": "Elegir un Plan",
  "Pay now": "Pagar ahora",
  "You'll be redirected to Stripe to complete payment securely.": "Será redirigido a Stripe para completar el pago de forma segura.",
  "Continue to Stripe": "Continuar a Stripe",
  "Fully Loaded": "Fully Loaded",
  "On": "Activado",
  "Off": "Desactivado",
  "Failed to load billing": "No se pudo cargar la facturación",
  "— billing not linked": "— facturación no vinculada",
  "— unable to load billing": "— no se pudo cargar la facturación",
  "No expenses yet.": "Aún no hay gastos.",
  "No customers yet.": "Aún no hay clientes.",
  "No vehicles yet.": "Aún no hay vehículos.",
  "Loading…": "Cargando…",
  "before costs": "antes de costos",
  "after all costs": "después de todos los costos",
  "commission this month": "comisión este mes",
  "in vehicles sold": "en vehículos vendidos",
  "on the lot now": "en el lote ahora",
  "— gross margin": "— margen bruto",
  "— net margin": "— margen neto",
  "operating expenses (excludes COGS)": "gastos operativos (excluye COGS)",
  "operating expenses (excludes COGS) · view all →": "gastos operativos (excluye COGS) · ver todo →",
  "on the floor plan": "en el plan de piso",
  "accrued interest to date": "interés acumulado a la fecha",
  "principal + fees to clear": "capital + cargos por liquidar",
  "due soon or overdue": "próximo a vencer o vencido",
  "Back to Vehicles": "Volver a Vehículos",
  "Every floored vehicle, what it's costing you daily, and what you owe the flooring company.": "Cada vehículo financiado, cuánto le cuesta diariamente y cuánto debe a la financiera.",
  "Notes & Appointments": "Notas y Citas",
  "Save": "Guardar",
  "This is the": "Este es el",
  "Any notes you save here are stored on the": "Cualquier nota que guarde aquí se almacena en el",
  "not the sales calendar.": "no en el calendario de ventas.",
  "Signed in as": "Sesión iniciada como",
  "Sales Rep Portal.": "Portal de Vendedor.",
  "Read-only access": "Acceso de solo lectura",
  "viewing live financials as": "viendo finanzas en vivo como",
  "You can leave review notes, but changes are disabled.": "Puede dejar notas de revisión, pero los cambios están deshabilitados.",
  "Exit portal": "Salir del portal",
  "No messages right now.": "No hay mensajes por ahora.",
  "Loading messages…": "Cargando mensajes…",
  "No vehicles in inventory.": "No hay vehículos en inventario.",
  "No sold vehicles in this period.": "No hay vehículos vendidos en este periodo.",
  "No sold vehicles to show.": "No hay vehículos vendidos para mostrar.",
  "No vehicles in inventory yet. Use + Add Vehicle to get started.": "Aún no hay vehículos en inventario. Use + Agregar Vehículo para comenzar.",
  "No vehicles sold in this period.": "No hay vehículos vendidos en este periodo.",
  "No customers match this search.": "Ningún cliente coincide con esta búsqueda.",
  "Total": "Total",
  "No vehicles were included in this filing.": "No se incluyeron vehículos en esta declaración.",
  "Full income statement": "Estado de ingresos completo",
  "Revenue": "Ingresos",
  "Vehicle Sales": "Ventas de Vehículos",
  "Add-On & Upcharge Revenue": "Ingresos por Extras y Recargos",
  "Total Revenue": "Ingresos Totales",
  "Cost of Goods Sold": "Costo de Ventas",
  "Vehicle Acquisition": "Adquisición del Vehículo",
  "Auction & Title Fees": "Cargos de Subasta y Título",
  "Reconditioning & Repairs": "Reacondicionamiento y Reparaciones",
  "Floor-Plan (Flooring)": "Plan de Piso (Financiamiento)",
  "Total COGS": "Costo de Ventas Total",
  "Total Operating Expenses": "Gastos Operativos Totales",
  "Net Profit": "Ganancia Neta",
  "Net Loss": "Pérdida Neta",
  "Floored this day": "Financiados este día",
  "Could not load leads.": "No se pudieron cargar los prospectos.",
  "Retry": "Reintentar",
  "No messages": "Sin mensajes",
  "total": "total",
  "unread": "sin leer",
  "Close a deal to crown your top rep.": "Cierre una venta para coronar a su mejor vendedor.",
  "Signed by": "Firmado por",
  "Dealership": "Concesionario",
  "Version": "Versión",
  "Accepted": "Aceptado",
  "Electronic Signature": "Firma Electrónica",
  "Date": "Fecha",
  "Plan": "Plan",
  "Amount": "Monto",
  "Status": "Estado",
  "Current Plan": "Plan Actual",
  "Billing cycle": "Ciclo de facturación",
  "Next charge": "Próximo cargo",
  "Includes": "Incluye",
  "Upgrade plan": "Mejorar plan",
  "Payment Method": "Método de Pago",
  "Amount due": "Monto adeudado",
  "Expense logging": "Registro de gastos",
  "Update payment method": "Actualizar método de pago",
  "Make a payment": "Hacer un pago",
  "Add payments to Expenses automatically": "Agregar pagos a Gastos automáticamente",
  "Notify me 3 days before billing": "Avisarme 3 días antes de la facturación",
  "When on, every subscription payment is logged in your": "Cuando está activo, cada pago de suscripción se registra en su",
  "section under Dealership Expense / Subscriptions —": "sección bajo Gasto del Concesionario / Suscripciones —",
  "so your books stay current without re-typing it.": "así sus libros se mantienen al día sin volver a escribirlo.",
  "When on, AutoVault emails you 3 days before each charge so": "Cuando está activo, AutoVault le envía un correo 3 días antes de cada cargo para",
  "you can confirm the card on file. A separate email always": "confirmar la tarjeta registrada. Un correo aparte siempre",
  "sends on the billing date itself.": "se envía el día de facturación.",
  "set a due date": "fije una fecha de vencimiento",
  " overdue by ": " de retraso ",
  " day ": " día ",
  " days ": " días ",
  "due today": "vence hoy",
  "in ": "en ",
  "Monthly Revenue": "Ingresos Mensuales",
  "live sessions": "sesiones en vivo",
  "Profitable Sales": "Ventas Rentables",
  "Loss Sales": "Ventas con Pérdida",
  "Showing": "Mostrando",
  "item(s)": "artículo(s)",
  "clear": "limpiar",
  "No expenses match these filters. Click Add Expense to log where money is going.": "Ningún gasto coincide con estos filtros. Haga clic en Agregar Gasto para registrar el dinero.",
  "No expenses attached to this vehicle yet — this will be the first.": "No hay gastos adjuntos a este vehículo — este será el primero.",
  "No recurring expenses yet — add one below.": "Aún no hay gastos recurrentes — agregue uno abajo.",
  "No documents yet. Scan a title, invoice": "Aún no hay documentos. Escanee un título, factura",
  "Already on": "Ya en",
  "Attaching to": "Adjuntando a",
  "No expenses in this period.": "No hay gastos en este periodo.",
  "No expenses logged yet.": "Aún no hay gastos registrados.",
  "No vehicles sitting right at break-even.": "No hay vehículos justo en el punto de equilibrio.",
  "No vehicles have been in inventory over": "Ningún vehículo ha estado en inventario más de",
  "days.": "días.",
  "vehicles paid off": "vehículos liquidados",
  "in flooring fees locked in": "en cargos de financiamiento cerrados",
  "No vehicles are being floored right now. Set up flooring from the Vehicles page to track floor-plan costs here.": "No hay vehículos financiados actualmente. Configure el financiamiento desde la página de Vehículos para rastrear costos aquí.",
  "No vehicles floored": "No hay vehículos financiados",
  "No add-ons yet. Click": "Aún no hay extras. Haga clic en",
  "to add warranties, or": "para agregar garantías, o",
  "No add-ons yet. Add the first one below.": "Aún no hay extras. Agregue el primero abajo.",
  "You typed a repair but haven't updated/added it yet": "Escribió una reparación pero aún no la actualizó/agregó",
  "You typed an add-on but haven't added it yet": "Escribió un extra pero aún no lo agregó",
  "annually": "anualmente",
  "day": "día",
  "per deal": "por venta",
  "Estimated Next Paycheck": "Próximo Pago Estimado",
  "No pay schedule on file": "No hay calendario de pago registrado",
  "Upload receipt (PDF or image)": "Subir recibo (PDF o imagen)",
  "Save Expense": "Guardar Gasto",
  "None": "Ninguno",
  "Generating…": "Generando…",
  "Auto generate": "Generar automáticamente",
  "All changes saved": "Todos los cambios guardados",
  "Not saved": "No guardado",
  "Unsaved changes": "Cambios sin guardar",
  "Change": "Cambiar",
  "Upload": "Subir",
  "Edit Employee": "Editar Empleado",
  "Monthly Salary": "Salario Mensual",
  "Commission Rate": "Tasa de Comisión",
  "Hourly Rate": "Tarifa por Hora",
  "Per deal": "Por venta",
  "Saving...": "Guardando...",
  "Failed to load dashboard data.": "No se pudieron cargar los datos del panel.",
  "Log out": "Cerrar sesión",
  "Log in as this rep": "Iniciar sesión como este vendedor",
  "Return to admin": "Volver al admin",
  "Add sticky note": "Agregar nota adhesiva",
  "This month vs last month": "Este mes vs mes anterior",
  "This": "Este",
  "Last": "Anterior",
  "Add Vehicle to Inventory": "Agregar Vehículo al Inventario",
  "Your Commission": "Su Comisión",
  "Sale price": "Precio de venta",
  "Commission rate": "Tasa de comisión",
  "Your commission": "Su comisión",
  "Grid Lines ON": "Líneas de Cuadrícula ACTIVADAS",
  "Add Grid Lines": "Agregar Líneas de Cuadrícula",
  "Decoding VIN…": "Decodificando VIN…",
  "Decoded:": "Decodificado:",
  "— add price to finish": "— agregue precio para terminar",
  "Set price": "Establecer precio",
  "potential": "potencial",
  "Paid off": "Liquidado",
  "Commission applies only on sold vehicles": "La comisión solo aplica en vehículos vendidos",
  " vehicle sales + add-ons": " ventas de vehículos + extras",
  " unit sold + add-ons": " unidad vendida + extras",
  "units sold + add-ons": "unidades vendidas + extras",
  " unit sold + add-ons": " unidad vendida + extras",
  "View every operating expense in this period, including recurring": "Ver todos los gastos operativos del periodo, incluidos recurrentes",
  "view all →": "ver todo →",
  "Full Year": "Año Completo",
  "This month": "Este mes",
  "Before costs": "Antes de costos",
  "After all costs": "Después de todos los costos",
  "Commission this month": "Comisión este mes",
  "In vehicles sold": "En vehículos vendidos",
  "On the lot now": "En el lote ahora",
  "Loading…": "Cargando…",
  "Total sold value": "Valor total vendido",
  "In this period": "En este periodo",
  "Set a due date": "Establecer fecha de vencimiento",
  "Earned from deals": "Ganado en ventas",
  "Staff (hourly + salary)": "Personal (por hora + salario)",
  "On the team": "En el equipo",
  "Vehicles sold to buyers": "Vehículos vendidos a compradores",
  "Sum of what they paid": "Suma de lo que pagaron",
  "Per customer": "Por cliente",
  "Phone & email captured": "Teléfono y correo capturados",
  "Vehicle sales + add-ons": "Ventas de vehículos + extras",
  "Unit sold + add-ons": "Unidad vendida + extras",
  "Units sold + add-ons": "Unidades vendidas + extras",
  "Gross margin": "Margen bruto",
  "Net margin": "Margen neto",
  "Operating expenses (excludes COGS) ·": "Gastos operativos (excluye COGS) ·",
  "On the floor plan": "En el plan de piso",
  "Accrued interest to date": "Intereses acumulados hasta la fecha",
  "Principal + fees to clear": "Capital + honorarios por liquidar",
  "Due soon or overdue": "Próximo vencer o vencido",
  "This period": "Este periodo",
  "Sold value": "Valor vendido",
  "Earned this period": "Ganado en este periodo",
  "Greater of base / commission": "Mayor de base / comisión",
  "Annualized": "Anualizado",
  "In-stock · click to filter": "En stock · clic para filtrar",
  "Units moved": "Unidades movidas",
  "Total sale price": "Precio total de venta",
  "Net, sold this month": "Neto, vendido este mes",
  "Spent on current stock": "Gastado en stock actual",
  "Recon + parts": "Recon + refacciones",
  "Collected this period": "Cobrado en este periodo",
  "Owed to reps": "Pendiente a vendedores",
  "All-in on current stock": "Total en stock actual",
  "Sold vehicles": "Vehículos vendidos",
  "Gross sales": "Ventas brutas",
  "Across deals": "En todas las ventas",
  "Click to view present titles": "Clic para ver títulos presentes",
  "Closed deals": "Ventas cerradas",
  "— Closed deals": "— Ventas cerradas",
  "Vehicles Sold This Month": "Vehículos Vendidos Este Mes",
  "sold ·": "vendidos ·",
  "Net P&L": "Ganancias y Pérdidas Netas",
  "This month vs last month · ": "Este mes vs mes anterior · ",
  "This": "Este",
  "Last": "Anterior",
  "Your AI assistant": "Tu asistente de IA",
  "Money in cars?": "¿Dinero en autos?",
  "Owed to reps?": "¿Pendiente a vendedores?",
  "Unpaid bills?": "¿Facturas impagas?",
  "Biggest expense?": "¿Mayor gasto?",
  "Ask Jenna anything...": "Pregúntale a Jenna...",
  "Scan a document": "Escanear un documento",
  "Hey, I'm Jenna 👋 your AI assistant. Ask me things like \"How much money do I have in cars?\" or \"How much do I owe my reps this month?\" — or tell me to scan a receipt to a vehicle.": "Hola, soy Jenna 👋 tu asistente de IA. Pregúntame cosas como \"¿Cuánto dinero tengo en autos?\" o \"¿Cuánto les debo a mis vendedores este mes?\" — o pídele que escanee un recibo a un vehículo.",
  "Saving…": "Guardando…",
  "Please add a subject and a message so we can help.": "Agregue un asunto y un mensaje para poder ayudarle.",
  "Couldn't send right now — try again in a moment.": "No se pudo enviar ahora — intente de nuevo en un momento.",
  "Sending…": "Enviando…",
  "Send Message": "Enviar Mensaje",
  "Passwords must match": "Las contraseñas deben coincidir",
  "Passwords match": "Las contraseñas coinciden",
  "Passwords do not match": "Las contraseñas no coinciden",
  "Send CPA invite": "Enviar invitación CPA",
  "Send invite": "Enviar invitación",
  "Loading inventory…": "Cargando inventario…",
  "Archive Sales Rep": "Archivar Vendedor",
  "All vehicles": "Todos los vehículos",
  "Select rep…": "Seleccionar vendedor…",
  "No vehicles on the floor plan right now.": "No hay vehículos en el plan de piso ahora.",
  "Select a day to see its sales and write appointments or notes.": "Seleccione un día para ver sus ventas y escribir citas o notas.",
  "Click a day to add flooring notes for it.": "Haga clic en un día para agregar notas de financiamiento.",
  "No vehicles sold in this period. Sales data will appear here once deals are completed and marked as sold.": "No hay vehículos vendidos en este periodo. Los datos de ventas aparecerán aquí cuando se completen y marquen como vendidos.",
  "Click any vehicle to open its deal jacket": "Haga clic en cualquier vehículo para abrir su carpeta de venta",
  "Click a customer to open their deal jacket": "Haga clic en un cliente para abrir su carpeta de venta",
  "Rest of Inventory": "Resto del Inventario",
  "Other Paid Customers": "Otros Clientes Pagados",
  "Paid customers": "Clientes pagados",
  "Active vehicles": "Vehículos activos",
  "Back to Messages": "Volver a Mensajes",
  "Back to Dashboard": "Volver al Panel",
  "Back to Sold Vehicles": "Volver a Vehículos Vendidos",
  "No vehicles sold in": "No hay vehículos vendidos en",
  "Total:": "Total:",
  "set your filing due date →": "fije su fecha de vencimiento de declaración →",
  "Next filing due:": "Próxima declaración vence:",
  "Collected since last filing": "Cobrado desde la última declaración",
  "Collected so far:": "Cobrado hasta ahora:",
  "nothing filed yet": "sin declarar aún",
  "No vehicles sold in this period.": "No hay vehículos vendidos en este periodo.",
  "Search conversations": "Buscar conversaciones",
  "Your messages": "Sus mensajes",
  "Select a conversation or start a new one.": "Seleccione una conversación o inicie una nueva.",
  "No conversations yet. Start a new message!": "Aún no hay conversaciones. ¡Inicie un mensaje nuevo!",
  "No conversations match your search.": "Ninguna conversación coincide con su búsqueda.",
  "No contacts found.": "No se encontraron contactos.",
  "New Message": "Nuevo Mensaje",
  "No leads yet. Add a lead to start tracking potential buyers.": "Aún no hay prospectos. Agregue uno para empezar a rastrear compradores potenciales.",
  "No leads match": "Ningún prospecto coincide con",
  "Looks like this'll be a profitable month.": "Parece que será un mes rentable.",
  "Let's keep an eye on the margins this month.": "Vigilemos los márgenes este mes.",
  "You're doing well this month.": "Le va bien este mes.",
  "And happy birthday to you! 🎉": "¡Y feliz cumpleaños para usted! 🎉",
  "Let me know if there's anything I can help you with.": "Avíseme si puedo ayudarle en algo.",
  "vehicles in current inventory": "vehículos en inventario actual",
  "in active inventory": "en inventario activo",
  " (% ": " (% ",
  "No leads yet. Click": "Aún no hay prospectos. Haga clic en",
  " to log a potential customer's name, phone, and email.": " para registrar nombre, teléfono y correo de un posible cliente.",
  "Confirm": "Confirmar",
  "Delete permanently?": "¿Eliminar permanentemente?",
  "Yes, delete": "Sí, eliminar",
  "No, keep it": "No, mantenerlo",
  "No signed agreement on file yet.": "Aún no hay acuerdo firmado registrado.",
  "Current plan": "Plan actual",
  "Available upgrade": "Mejora disponible",
  "Available upgrades": "Mejoras disponibles",
  "mo": "mes",
  "Upgrade": "Mejorar",
  "You're on the top plan — there's nothing higher to upgrade to.": "Está en el plan más alto — no hay nada superior para mejorar.",
  "Payment Past Due": "Pago Vencido",
  "Make a Payment": "Hacer un Pago",
  "Due date": "Fecha de vencimiento",
  "Paying with": "Pago con",
  "Card on file": "Tarjeta registrada",
  "You'll be redirected to Stripe to pay the open invoice securely.": "Será redirigido a Stripe para pagar la factura pendiente de forma segura.",
  "Your account is current — no payment is due.": "Su cuenta está al día — no hay pago pendiente.",
  "You'll be redirected to Stripe's secure billing portal to update your card. No card details are stored in AutoVault.": "Será redirigido al portal seguro de Stripe para actualizar su tarjeta. No se almacenan datos de tarjeta en AutoVault.",
  "Starting checkout…": "Iniciando pago…",
  "Redirecting to Stripe": "Redirigiendo a Stripe",
  "Unable to start upgrade": "No se pudo iniciar la mejora",
  "Opening Stripe…": "Abriendo Stripe…",
  "Secure billing portal": "Portal seguro de facturación",
  "Unable to open billing portal": "No se pudo abrir el portal de facturación",
  "Starting payment…": "Iniciando pago…",
  "Unable to start payment": "No se pudo iniciar el pago",
  "No checkout URL returned": "No se devolvió URL de pago",
  "No portal URL returned": "No se devolvió URL del portal",
  "No payment URL returned": "No se devolvió URL de pago",
  "No card details are stored in AutoVault.": "No se almacenan datos de tarjeta en AutoVault.",
  "months": "meses",
  "year": "año",
  "yr": "año",
  "Gross Margin": "Margen Bruto",
  "Net Margin": "Margen Neto",
  " Unit Sold + Add-ons": " Unidad Vendida + Extras",
  " Units Sold + Add-ons": " Unidades Vendidas + Extras",
  "closed deals": "ventas cerradas",
  "Viewing as": "Viendo como",
  "secure admin support session. Changes are audited.": "sesión de soporte de administrador seguro. Los cambios quedan registrados.",
  "View every operating expense in this period, including recurring": "Ver todos los gastos operativos del periodo, incluidos recurrentes",
  "Revenue Allocation": "Distribución de Ingresos",
  "Where every dollar goes": "A dónde va cada dólar",
  "Full income statement": "Estado de ingresos completo",
  "Profit & Loss Statement": "Estado de Ganancias y Pérdidas",
  "Floored this day": "Financiados este día",
  "This is the": "Este es el",
  "Flooring Calendar": "Calendario de Financiamiento",
  "Any notes you save here are stored on the": "Cualquier nota que guarde aquí se almacena en el",
  "flooring calendar": "calendario de financiamiento",
  "not the sales calendar.": "no en el calendario de ventas.",
  "No vehicles on the floor plan right now.": "No hay vehículos en el plan de piso ahora.",
  "Back to Vehicles": "Volver a Vehículos",
  "Every floored vehicle, what it's costing you daily, and what you owe the flooring company.": "Cada vehículo financiado, cuánto le cuesta diariamente y cuánto debe a la financiera.",
  "Loading messages…": "Cargando mensajes…",
  "No messages right now.": "No hay mensajes por ahora.",
  "Total:": "Total:",
  "vehicles paid off": "vehículos liquidados",
  "in flooring fees locked in": "en cargos de financiamiento cerrados",
  "No vehicles are being floored right now. Set up flooring from the Vehicles page to track floor-plan costs here.": "No hay vehículos financiados actualmente. Configure el financiamiento desde la página de Vehículos para rastrear costos aquí.",
  "No vehicles floored": "No hay vehículos financiados",
  "No vehicles in inventory.": "No hay vehículos en inventario.",
  "No sold vehicles in this period.": "No hay vehículos vendidos en este periodo.",
  "No sold vehicles to show.": "No hay vehículos vendidos para mostrar.",
  "No vehicles in inventory yet. Use + Add Vehicle to get started.": "Aún no hay vehículos en inventario. Use + Agregar Vehículo para comenzar.",
  "No vehicles sold in this period.": "No hay vehículos vendidos en este periodo.",
  "No vehicles sold in": "No hay vehículos vendidos en",
  "No customers match this search.": "Ningún cliente coincide con esta búsqueda.",
  "No vehicles were included in this filing.": "No se incluyeron vehículos en esta declaración.",
  "No vehicles sitting right at break-even.": "No hay vehículos justo en el punto de equilibrio.",
  "No expenses in this period.": "No hay gastos en este periodo.",
  "No expenses logged yet.": "Aún no hay gastos registrados.",
  "No vehicles have been in inventory over": "Ningún vehículo ha estado en inventario más de",
  "days.": "días.",
  "No expenses match these filters. Click Add Expense to log where money is going.": "Ningún gasto coincide con estos filtros. Haga clic en Agregar Gasto para registrar el dinero.",
  "No expenses attached to this vehicle yet — this will be the first.": "No hay gastos adjuntos a este vehículo — este será el primero.",
  "No recurring expenses yet — add one below.": "Aún no hay gastos recurrentes — agregue uno abajo.",
  "No add-ons yet. Click": "Aún no hay extras. Haga clic en",
  "to add warranties, or": "para agregar garantías, o",
  "No add-ons yet. Add the first one below.": "Aún no hay extras. Agregue el primero abajo.",
  "You typed a repair but haven't updated/added it yet": "Escribió una reparación pero aún no la actualizó/agregó",
  "You typed an add-on but haven't added it yet": "Escribió un extra pero aún no lo agregó",
  "Set price": "Establecer precio",
  "potential": "potencial",
  "Grid Lines ON": "Líneas de Cuadrícula ACTIVADAS",
  "Add Grid Lines": "Agregar Líneas de Cuadrícula",
  "No documents yet. Scan a title, invoice": "Aún no hay documentos. Escanee un título, factura",
  "No other paid customers yet.": "Aún no hay otros clientes pagados.",
  "All vehicles are sold.": "Todos los vehículos están vendidos.",
  "No employees on payroll yet.": "Aún no hay empleados en nómina.",
  "No filings recorded yet.": "Aún no hay declaraciones registradas.",
  "No sales in this period.": "No hay ventas en este periodo.",
  "No cars sold in": "No hay autos vendidos en",
  "No payments recorded this year yet.": "Aún no hay pagos registrados este año.",
  "No receipt yet. Scan or upload one.": "Aún no hay recibo. Escanee o suba uno.",
  "All vehicles": "Todos los vehículos",
  "Search conversations": "Buscar conversaciones",
  "Your messages": "Sus mensajes",
  "Select a conversation or start a new one.": "Seleccione una conversación o inicie una nueva.",
  "No conversations yet. Start a new message!": "Aún no hay conversaciones. ¡Inicie un mensaje nuevo!",
  "No conversations match your search.": "Ninguna conversación coincide con su búsqueda.",
  "No contacts found.": "No se encontraron contactos.",
  "New Message": "Nuevo Mensaje"
};
  g.AV_MONTH_EN2ES = {
  "January": "Enero",
  "February": "Febrero",
  "March": "Marzo",
  "April": "Abril",
  "May": "Mayo",
  "June": "Junio",
  "July": "Julio",
  "August": "Agosto",
  "September": "Septiembre",
  "October": "Octubre",
  "November": "Noviembre",
  "December": "Diciembre",
  "Jan": "Ene",
  "Feb": "Feb",
  "Mar": "Mar",
  "Apr": "Abr",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Ago",
  "Sep": "Sep",
  "Sept": "Sep",
  "Oct": "Oct",
  "Nov": "Nov",
  "Dec": "Dic"
};
  g.AV_MONTH_ES2EN = (function () {
    var o = {};
    for (var k in g.AV_MONTH_EN2ES) {
      if (o[g.AV_MONTH_EN2ES[k]] === undefined) o[g.AV_MONTH_EN2ES[k]] = k;
    }
    return o;
  })();
})(typeof window !== "undefined" ? window : globalThis);
