window.AV_LANDING_EXTRA = {
  "Get Started — Free": "Comenzar — Gratis",
  "Skip to content": "Saltar al contenido",
  "Switch theme": "Cambiar tema",
  "Toggle theme": "Cambiar tema",
  "Open menu": "Abrir menú",
  "Close menu": "Cerrar menú",
  "Switch to light mode": "Cambiar a modo claro",
  "Switch to dark mode": "Cambiar a modo oscuro",
  "Show password": "Mostrar contraseña",
  "Every number. Every vehicle. Every dollar. All at the touch of a button.": "Cada número. Cada vehículo. Cada dólar. Todo al alcance de un botón.",
  "One live dashboard for every vehicle and every dollar.": "Un panel en vivo para cada vehículo y cada dólar.",
  "128 vehicles": "128 vehículos",
  "68 units": "68 unidades",
  "Jul 31": "31 jul",
  "Owed $9,280": "Debido $9,280",
  "Net margin 15%": "Margen neto 15%",
  "P&L": "Gan. y pérd.",
  "Jul 31, 2026": "31 jul 2026",
  "July 31, 2026": "31 de julio de 2026",
  "Jul 31 · $18,240 collected": "31 jul · $18,240 recaudados",
  "Jul 9 · +$4,755 profit": "9 jul · +$4,755 de ganancia",
  "Jul 11 · Auction day": "11 jul · Día de subasta",
  "Jul 14 · +$3,690 profit": "14 jul · +$3,690 de ganancia",
  "Jul 24 · Manheim Las Vegas": "24 jul · Manheim Las Vegas",
  "The dashboard — your whole operation, live": "El panel — toda tu operación, en vivo",
  "Net profit, revenue, gross profit and commissions owed, updated in real time — plus your top-selling reps and your entire inventory mix at a glance.": "Ganancia neta, ingresos, ganancia bruta y comisiones pendientes, actualizados en tiempo real — más tus mejores vendedores y todo tu inventario de un vistazo.",
  "Inventory — true profit on every VIN": "Inventario — ganancia real en cada VIN",
  "Every vehicle carries its real all-in cost: purchase, auction and doc fees, repairs, add-ons and flooring — so you see net profit and ROI per car, not sticker vs. sale.": "Cada vehículo lleva su costo real total: compra, tarifas de subasta y documentos, reparaciones, extras y flooring — para que veas la ganancia neta y el ROI por auto, no precio de lista vs. venta.",
  "Sales Tax — always filing-ready": "Impuesto — siempre listo para declarar",
  "Tax collected is organized by state and by VIN, with filing reminders and a quarterly schedule, so you never scramble when a deadline lands.": "El impuesto recaudado se organiza por estado y por VIN, con recordatorios de declaración y un calendario trimestral, para que nunca corras cuando vence la fecha.",
  "Payroll — pay from what they closed": "Nómina — paga según lo que cerraron",
  "Base pay plus commission calculates itself from every deal they close, hourly staff clock in automatically, and each payout is logged with proof.": "El salario base más comisión se calcula solo con cada venta que cierran, el personal por hora registra su tiempo automáticamente, y cada pago queda con comprobante.",
  "Profit & Loss — tax-ready in one click": "Ganancias y pérdidas — listo para impuestos en un clic",
  "A live P&L for this week, this month and this year — revenue, cost of goods, commissions and net profit — organized and ready to hand to your accountant.": "Un estado de ganancias y pérdidas en vivo de esta semana, este mes y este año — ingresos, costo de bienes, comisiones y ganancia neta — organizado y listo para tu contador.",
  "Calendar — never miss a filing or payday": "Calendario — no te pierdas una declaración ni un día de pago",
  "Filing dates, payroll runs, auction days and title pickups on one calendar so the whole desk stays ahead of deadlines.": "Fechas de declaración, corridas de nómina, días de subasta y recolecta de títulos en un solo calendario para que todo el escritorio se adelante a las fechas límite.",
  "Helps you stay profitable": "Te ayuda a seguir rentable",
  "Takes action for you": "Toma acción por ti",
  "In your pocket, one click away": "En tu bolsillo, a un clic",
  "AI Assistant for AutoVault": "Asistente de IA para AutoVault",
  "Ask Jenna anything…": "Pregúntale lo que sea a Jenna…",
  "avg. hidden profit dealers surface after switching": "ganancia oculta promedio que los dealers descubren al cambiarse",
  "vehicles tracked per lot, on average": "vehículos rastreados por lote, en promedio",
  "states filing tax-ready from one platform": "estados declarando impuestos desde una sola plataforma",
  "“I found $9,000 in flooring costs I’d stopped tracking. AutoVault paid for itself the first week.”": "“Encontré $9,000 en costos de flooring que había dejado de rastrear. AutoVault se pagó solo la primera semana.”",
  "· Independent dealer, 40-car lot": "· Dealer independiente, lote de 40 autos",
  "“Tax season used to eat three weeks. Now my accountant logs in and files — done.”": "“La temporada de impuestos se comía tres semanas. Ahora mi contador entra y declara — listo.”",
  "· Riverside Auto Group": "· Riverside Auto Group",
  "“Every rep sees their own numbers, so the commission arguments stopped overnight.”": "“Cada vendedor ve sus propios números, así que las discusiones de comisión se acabaron de un día para otro.”",
  "· Used-car manager": "· Gerente de autos usados",
  "Cost, sale price, and margin on every vehicle — so a thin deal shows up before you shake on it, not after.": "Costo, precio de venta y margen en cada vehículo — para que un trato delgado se vea antes de cerrarlo, no después.",
  "A sale updates inventory, transactions, payments, and commissions at once — no more re-typing the same deal four times.": "Una venta actualiza inventario, transacciones, pagos y comisiones a la vez — sin volver a capturar el mismo trato cuatro veces.",
  "Every vehicle, payment, and expense logged with a paper trail your accountant and an auditor can both follow.": "Cada vehículo, pago y gasto queda registrado con un rastro que tu contador y un auditor pueden seguir.",
  "Cloud-based, role-based access. Owner, sales manager, or CPA — everyone sees the same live numbers from any device.": "En la nube, con acceso por rol. Dueño, gerente de ventas o CPA — todos ven los mismos números en vivo desde cualquier dispositivo.",
  "A day-to-day calendar.": "Un calendario del día a día.",
  "Everything happening today — auctions, filings, follow-ups — at a glance.": "Todo lo de hoy — subastas, declaraciones, seguimientos — de un vistazo.",
  "Notes & to-dos.": "Notas y pendientes.",
  "Jot down what matters and check it off. Never lose track again.": "Anota lo importante y márcalo. No vuelvas a perder el hilo.",
  "Sticky reminders.": "Recordatorios adhesivos.",
  "Keep the important stuff front and center to stay sharp all day.": "Mantén lo importante al frente para seguir al día todo el día.",
  "One login, one desk.": "Un inicio de sesión, un escritorio.",
  "Your whole operation, one click at the tip of your fingertips.": "Toda tu operación, a un clic de tus dedos.",
  "Instead of paperwork spread all over your desk, it’s all one click away. Keep it all organized, sharp, and in one place.": "En vez de papeles por todo el escritorio, todo está a un clic. Organizado, claro y en un solo lugar.",
  "Instead of paperwork spread all over your desk, it's all one click away. Keep it all organized, sharp, and in one place.": "En vez de papeles por todo el escritorio, todo está a un clic. Organizado, claro y en un solo lugar.",
  "My Desk": "Mi escritorio",
  "Wed, Jul 15": "Mié, 15 jul",
  "Today's notes": "Notas de hoy",
  "Log Silverado expenses": "Registrar gastos del Silverado",
  "Call Manheim about Thursday's run": "Llamar a Manheim sobre la corrida del jueves",
  "Follow up on Jeep title": "Dar seguimiento al título del Jeep",
  "Review this week's P&L": "Revisar las ganancias y pérdidas de esta semana",
  "Payroll runs Friday!": "¡La nómina corre el viernes!",
  "Title for Silverado ✓": "Título del Silverado ✓",
  "List a car in": "Registra un auto en",
  ", close it in": ", ciérralo en",
  "Transactions": "Transacciones",
  ", and the sale flows straight into": ", y la venta fluye directo a",
  "Payments": "Pagos",
  "Sales Reps": "Vendedores",
  ", and your live": ", y tus",
  "Reports": "Reportes",
  "— no double entry, no drift between files.": "— sin doble captura, sin descuadres entre archivos.",
  "Sold Vehicles": "Vehículos vendidos",
  "Auctions": "Subastas",
  "Expenses": "Gastos",
  "Customers": "Clientes",
  "Tasks": "Tareas",
  "Settings": "Ajustes",
  "Titles in hand": "Títulos en mano",
  "5 titles pending": "5 títulos pendientes",
  "Total purchase cost": "Costo total de compra",
  "6 vehicles": "6 vehículos",
  "Total gross profit": "Ganancia bruta total",
  "Total net profit": "Ganancia neta total",
  "after all costs": "después de todos los costos",
  "Avg ROI": "ROI promedio",
  "per vehicle": "por vehículo",
  "Avg gross profit": "Ganancia bruta promedio",
  "Vehicle Profit Breakdown": "Desglose de ganancia por vehículo",
  "This month · showing 6 of 128 vehicles": "Este mes · mostrando 6 de 128 vehículos",
  "+$19,246 net profit": "+$19,246 ganancia neta",
  "Purchase": "Compra",
  "Auction fees": "Tarifas de subasta",
  "Flooring fees": "Tarifas de flooring",
  "Sales tax": "Impuesto",
  "Profit": "Ganancia",
  "1C4RJFAG3JC411882 · Sold": "1C4RJFAG3JC411882 · Vendido",
  "1FTFW1E5XMFA12345 · In stock": "1FTFW1E5XMFA12345 · En inventario",
  "1HGCV1F34LA098213 · In stock": "1HGCV1F34LA098213 · En inventario",
  "4T1G11AK5NU552310 · In stock": "4T1G11AK5NU552310 · En inventario",
  "1N4BL4CV5NN315502 · In stock": "1N4BL4CV5NN315502 · En inventario",
  "3GCUYDED5KG215566 · Underwater": "3GCUYDED5KG215566 · En pérdida",
  "All vehicles": "Todos los vehículos",
  "Sales tax is collected on the buyer's behalf and remitted to the state — profit is your real margin after purchase, auction, and flooring costs.": "El impuesto se recauda a nombre del comprador y se remite al estado — la ganancia es tu margen real después de compra, subasta y flooring.",
  "Quarterly filing · reminder set 7 days before": "Declaración trimestral · recordatorio 7 días antes",
  "Due soon": "Vence pronto",
  "Filing schedule · Quarterly": "Calendario de declaración · Trimestral",
  "Jan – Mar · filed Apr 30": "Ene – mar · declarado 30 abr",
  "Apr – Jun · due Jul 31": "Abr – jun · vence 31 jul",
  "Jul – Sep · due Oct 31": "Jul – sep · vence 31 oct",
  "Upcoming": "Próximo",
  "Oct – Dec · due Jan 31": "Oct – dic · vence 31 ene",
  "Collected this quarter": "Recaudado este trimestre",
  "Organized by state · tied to each VIN": "Organizado por estado · ligado a cada VIN",
  "By vehicle · recent": "Por vehículo · reciente",
  "CA · On file": "CA · Registrado",
  "NV · On file": "NV · Registrado",
  "CA · Filed": "CA · Declarado",
  "Choose a filing frequency and set due-date reminders for each state you sell in — AutoVault keeps every dollar of collected tax organized, sorted by state, and export-ready, so you never miss a deadline or rebuild it from a spreadsheet.": "Elige una frecuencia de declaración y pon recordatorios de fecha límite para cada estado donde vendas — AutoVault mantiene cada dólar de impuesto organizado, ordenado por estado y listo para exportar, para que no se te pase una fecha ni lo armes otra vez desde una hoja de cálculo.",
  "This week · tap any deal": "Esta semana · toca cualquier trato",
  "Deals": "Tratos",
  "Bought $18,400 · Sold $21,900": "Compró $18,400 · Vendió $21,900",
  "Bought $16,900 · Sold $19,600": "Compró $16,900 · Vendió $19,600",
  "Bought $15,200 · Sold $18,100": "Compró $15,200 · Vendió $18,100",
  "Flipping": "En proceso",
  "Bought $14,300 · asking $17,500": "Compró $14,300 · pide $17,500",
  "Log a wholesale deal": "Registrar un trato mayorista",
  "The wholesale game doesn't wait — and neither should you. Stop scribbling deals in a notebook and guessing what you made. AutoVault puts every number, every vehicle, and every wholesale deal right in your pocket. Buy it, flip it, log it — and watch your real profit land the second the deal closes.": "El juego mayorista no espera — y tú tampoco deberías. Deja de anotar tratos en un cuaderno y adivinar lo que ganaste. AutoVault pone cada número, cada vehículo y cada trato mayorista en tu bolsillo. Cómpralo, voltéalo, regístralo — y ve tu ganancia real en el segundo en que cierra el trato.",
  "Every deal in your pocket.": "Cada trato en tu bolsillo.",
  "All your numbers, vehicles, and wholesale deals — one tap away, wherever you are.": "Todos tus números, vehículos y tratos mayoristas — a un toque, donde sea que estés.",
  "Profit the moment you flip.": "Ganancia en el momento en que volteas.",
  "Cost in, sale out, profit clear. No math, no notebook, no guessing.": "Costo de entrada, venta de salida, ganancia clara. Sin cuentas, sin cuaderno, sin adivinar.",
  "Built for speed.": "Hecho para la velocidad.",
  "Log a buy at the auction and a sale on the lot without breaking stride.": "Registra una compra en la subasta y una venta en el lote sin detenerte.",
  "Nothing slips through.": "Nada se te escapa.",
  "Track every unit from the second you buy it to the day it's gone.": "Rastrea cada unidad desde el segundo que la compras hasta el día que se va.",
  "One tap. Every deal. Total control.": "Un toque. Cada trato. Control total.",
  "Wholesale Auction Board": "Tablero de subastas mayoristas",
  "This week · Jul 6 – 12, 2026": "Esta semana · 6 – 12 jul 2026",
  "18 cars in motion": "18 autos en movimiento",
  "Sold at auction": "Vendidos en subasta",
  "this week": "esta semana",
  "Rerunning": "Repitiendo",
  "back on the block": "de vuelta en el bloque",
  "Dealer-to-dealer": "Dealer a dealer",
  "direct sales": "ventas directas",
  "Where your cars are selling": "Dónde se venden tus autos",
  "Mon": "Lun",
  "Tue": "Mar",
  "Wed": "Mié",
  "Thu": "Jue",
  "Fri": "Vie",
  "Sat": "Sáb",
  "Sun": "Dom",
  "3 cars": "3 autos",
  "4 cars": "4 autos",
  "Where your cars are": "Dónde están tus autos",
  "8 at auction": "8 en subasta",
  "units": "unidades",
  "unit": "unidad",
  "Riverside, CA · 38% of lot": "Riverside, CA · 38% del lote",
  "Las Vegas, NV · 25% of lot": "Las Vegas, NV · 25% del lote",
  "Fontana, CA · 25% of lot": "Fontana, CA · 25% del lote",
  "Phoenix, AZ · 12% of lot": "Phoenix, AZ · 12% del lote",
  "The spreadsheet stack": "El montón de hojas de cálculo",
  "Numbers never match.": "Los números nunca cuadran.",
  "Inventory, sales, and payments live in separate files that drift out of sync.": "Inventario, ventas y pagos viven en archivos separados que se desincronizan.",
  "Commissions get argued.": "Se discute por las comisiones.",
  "No single source of truth for who sold what and what they're owed.": "No hay una sola fuente de verdad de quién vendió qué y cuánto se les debe.",
  "Tax season is a scramble.": "La temporada de impuestos es un caos.",
  "Weeks spent rebuilding records your CPA can't read.": "Semanas reconstruyendo registros que tu CPA no puede leer.",
  "You find out too late.": "Te enteras demasiado tarde.",
  "A thin-margin deal only shows up after the money's gone.": "Un trato de margen delgado solo aparece cuando el dinero ya se fue.",
  "One connected ledger.": "Un libro contable conectado.",
  "Every vehicle, sale, and payment updates the same live P&L.": "Cada vehículo, venta y pago actualiza las mismas ganancias y pérdidas en vivo.",
  "Commissions calculate themselves.": "Las comisiones se calculan solas.",
  "Reps and payroll see the same numbers, automatically.": "Vendedores y nómina ven los mismos números, automáticamente.",
  "Export-ready for your CPA.": "Listo para exportar a tu CPA.",
  "Give your accountant secure access instead of a shoebox.": "Dale a tu contador acceso seguro en vez de una caja de recibos.",
  "Margin in real time.": "Margen en tiempo real.",
  "Know the profit on a deal before you shake on it.": "Conoce la ganancia de un trato antes de cerrarlo.",
  "Purchase price, auction & doc fees, repairs, add-ons, flooring, and days on the lot roll into one true net-profit and ROI number — so you know which cars made money and which went underwater.": "Precio de compra, tarifas de subasta y documentos, reparaciones, extras, flooring y días en el lote se juntan en un número real de ganancia neta y ROI — para que sepas qué autos ganaron y cuáles se fueron a pérdida.",
  "The tax you collect is captured on every sale and tied to the VIN, then organized by your filing frequency with the next due date front and center. No more rebuilding it at quarter-end.": "El impuesto que recaudas se captura en cada venta y se liga al VIN, luego se organiza según tu frecuencia de declaración con la próxima fecha al frente. Se acabó reconstruirlo al cierre del trimestre.",
  "Salespeople on base plus commission, mechanics and lot staff hourly, managers on salary — all calculated automatically, with every payout logged and proof kept on file.": "Vendedores con base más comisión, mecánicos y personal del lote por hora, gerentes con salario — todo calculado automáticamente, con cada pago registrado y el comprobante en archivo.",
  "Revenue minus cost of goods, commissions, and overhead — with gross and net margin — shows exactly where the money goes and where you're losing it, updated as deals close.": "Ingresos menos costo de bienes, comisiones y gastos generales — con margen bruto y neto — muestra exactamente a dónde va el dinero y dónde lo pierdes, actualizado al cerrar cada trato.",
  "Our mission": "Nuestra misión",
  "From independent lots to wholesalers, our mission is to put every number that runs a dealership — inventory, true profit per VIN, sales tax, payroll, flooring, and P&L — into one login. So you always know exactly where the money goes, and keep more of it.": "De lotes independientes a mayoristas, nuestra misión es poner cada número que mueve un concesionario — inventario, ganancia real por VIN, impuesto, nómina, flooring y ganancias y pérdidas — en un solo inicio de sesión. Para que siempre sepas a dónde va el dinero, y te quedes con más.",
  "No enterprise price tag. No spreadsheet chaos. Just the numbers that keep you profitable, tracked automatically — from the day a car hits the lot to the day it's sold, paid out, and filed.": "Sin precio de empresa grande. Sin caos de hojas de cálculo. Solo los números que te mantienen rentable, rastreados automáticamente — desde el día que un auto llega al lote hasta el día que se vende, se paga y se declara.",
  "Every feature comes from real dealership workflows — auctions, flooring, titles, commissions — not a boardroom.": "Cada función nace de flujos reales de concesionario — subastas, flooring, títulos, comisiones — no de una sala de juntas.",
  "From auction fees to rep commissions, nothing slips through the cracks or gets lost in a text thread.": "De tarifas de subasta a comisiones de vendedores, nada se cuela ni se pierde en un hilo de mensajes.",
  "See true profit on every deal — and catch the cars quietly losing money before they cost you.": "Ve la ganancia real en cada trato — y detecta los autos que pierden dinero en silencio antes de que te cuesten.",
  "Inventory, taxes, payroll, calendar, notes and your team — all in one place, on any device.": "Inventario, impuestos, nómina, calendario, notas y tu equipo — todo en un lugar, en cualquier dispositivo.",
  "The difference between a good dealership and a great one is": "La diferencia entre un buen concesionario y uno excelente es",
  "knowing every number.": "conocer cada número.",
  "Questions, answered.": "Preguntas, respondidas.",
  "Is my data secure?": "¿Mis datos están seguros?",
  "Your data is encrypted in transit and at rest, protected by access controls and regular security reviews. Your dealership’s data is yours — export or delete it anytime.": "Tus datos se cifran en tránsito y en reposo, protegidos con controles de acceso y revisiones de seguridad. Los datos de tu concesionario son tuyos — expórtalos o elimínalos cuando quieras.",
  "Your data is encrypted in transit and at rest, protected by access controls and regular security reviews. Your dealership's data is yours — export or delete it anytime.": "Tus datos se cifran en tránsito y en reposo, protegidos con controles de acceso y revisiones de seguridad. Los datos de tu concesionario son tuyos — expórtalos o elimínalos cuando quieras.",
  "Can my accountant log in?": "¿Puede entrar mi contador?",
  "Yes. A CPA / accountant login is included, so your accountant can file state taxes and review the numbers without you emailing spreadsheets.": "Sí. Se incluye un acceso para CPA / contador, para que declare impuestos estatales y revise los números sin que le envíes hojas de cálculo.",
  "What happens after my free month?": "¿Qué pasa después de mi mes gratis?",
  "You’re billed $99.99/mo — no setup fees, no long-term contract. Cancel anytime and you won’t be charged again.": "Se te cobra $99.99/mes — sin cuota de instalación, sin contrato a largo plazo. Cancela cuando quieras y no se te vuelve a cobrar.",
  "You're billed $99.99/mo — no setup fees, no long-term contract. Cancel anytime and you won't be charged again.": "Se te cobra $99.99/mes — sin cuota de instalación, sin contrato a largo plazo. Cancela cuando quieras y no se te vuelve a cobrar.",
  "Do I need to install anything?": "¿Tengo que instalar algo?",
  "No. AutoVault runs in your browser and works on desktop, tablet, and phone. Add your vehicles and you’re running the same day.": "No. AutoVault corre en tu navegador y funciona en computadora, tablet y teléfono. Agrega tus vehículos y ese mismo día ya estás operando.",
  "No. AutoVault runs in your browser and works on desktop, tablet, and phone. Add your vehicles and you're running the same day.": "No. AutoVault corre en tu navegador y funciona en computadora, tablet y teléfono. Agrega tus vehículos y ese mismo día ya estás operando.",
  "Is there a per-vehicle or per-user charge?": "¿Hay cobro por vehículo o por usuario?",
  "No. Unlimited vehicles, VINs, and users are included — one flat price for your whole dealership.": "No. Vehículos, VIN y usuarios ilimitados están incluidos — un precio fijo para todo tu concesionario.",
  "Will it fit how my lot actually runs?": "¿Se adapta a cómo opera mi lote?",
  "AutoVault was built with dealers for the real workflow — auctions, flooring, titles, commissions, and filings — not a generic CRM bolted onto cars.": "AutoVault se hizo con dealers para el flujo real — subastas, flooring, títulos, comisiones y declaraciones — no un CRM genérico pegado a autos.",
  "Get your": "Obtén tu",
  "first month free.": "primer mes gratis.",
  "Get full access to every module and start running your dealership on AutoVault today — at our introductory rate. Lock it in while it lasts.": "Obtén acceso completo a cada módulo y empieza a operar tu concesionario en AutoVault hoy — a nuestra tarifa de introducción. Asegúrala mientras dure.",
  "first month · then $99.99/mo": "primer mes · luego $99.99/mes",
  "Unlimited vehicles, VINs & users": "Vehículos, VIN y usuarios ilimitados",
  "— no per-seat charges.": "— sin cobro por asiento.",
  "Every module included": "Cada módulo incluido",
  "— inventory, sales tax, payroll, P&L, and Jenna AI.": "— inventario, impuesto, nómina, ganancias y pérdidas, y Jenna AI.",
  "Cancel anytime": "Cancela cuando quieras",
  "— no setup fees, no long-term contract.": "— sin cuota de instalación, sin contrato a largo plazo.",
  "Your first month is free. A card is required at checkout so billing can start automatically after the free month.": "Tu primer mes es gratis. Se requiere una tarjeta en el pago para que la facturación empiece sola después del mes gratis.",
  "Full name": "Nombre completo",
  "Work email": "Correo de trabajo",
  "Phone number": "Número de teléfono",
  "Dealership name": "Nombre del concesionario",
  "Select state": "Elige el estado",
  "ZIP Code": "Código postal",
  "Jane Dealer": "Juana Dealer",
  "e.g. 90210": "ej. 90210",
  "We respect your privacy. No spam, ever.": "Respetamos tu privacidad. Nunca spam.",
  "One plan. Fully loaded.": "Un plan. Completo.",
  "Everything AutoVault does, in one login. Your first month is free, then $99.99/mo — no setup fees, cancel anytime.": "Todo lo que hace AutoVault, en un inicio de sesión. Tu primer mes es gratis, luego $99.99/mes — sin cuota de instalación, cancela cuando quieras.",
  "Everything included": "Todo incluido",
  "One plan, every feature — the entire platform to run your dealership, from inventory and profit to taxes, payroll, and Jenna, in a single login.": "Un plan, cada función — toda la plataforma para operar tu concesionario, de inventario y ganancia a impuestos, nómina y Jenna, en un solo inicio de sesión.",
  "1st month free": "1.er mes gratis",
  "Jenna AI assistant": "Asistente Jenna AI",
  "— the AI built for dealerships; ask about your lot, profit or deals and she answers instantly & takes action": "— la IA hecha para concesionarios; pregúntale por tu lote, ganancia o tratos y responde al instante y toma acción",
  "Full inventory": "Inventario completo",
  "— every vehicle tracked to its VIN, with real profit per unit": "— cada vehículo rastreado a su VIN, con ganancia real por unidad",
  "Customer deals & sales": "Tratos y ventas de clientes",
  "— log every retail deal end to end": "— registra cada trato al menudeo de principio a fin",
  "Track flooring costs": "Rastrea costos de flooring",
  "on every unit": "en cada unidad",
  "Log every expense": "Registra cada gasto",
  "— reconditioning, insurance, transport & fees": "— reacondicionamiento, seguro, transporte y tarifas",
  "Total invested per vehicle": "Total invertido por vehículo",
  "— know exactly what you're into each car for": "— sabe exactamente en cuánto estás en cada auto",
  "Title tracking": "Seguimiento de títulos",
  "— which titles are in hand, which aren't": "— qué títulos tienes en mano y cuáles no",
  "— sales tax organized by state, with filing reminders": "— impuesto organizado por estado, con recordatorios de declaración",
  "Tax-ready profit & loss": "Ganancias y pérdidas listas para impuestos",
  "— live this week, month & year, ready for your accountant": "— en vivo esta semana, mes y año, listo para tu contador",
  "— your accountant files & reviews every number": "— tu contador declara y revisa cada número",
  "Sales rep payroll & commission": "Nómina y comisión de vendedores",
  "— pay every rep from the deals they closed": "— paga a cada vendedor con los tratos que cerró",
  "Run it all from your phone": "Opéralo todo desde tu teléfono",
  "— everything on desktop works in your pocket": "— todo lo del escritorio funciona en tu bolsillo",
  "Check your email to finish setting up your dashboard.": "Revisa tu correo para terminar de configurar tu panel.",
  "The all-in-one dealership operating system. Built by dealers, backed by experience.": "El sistema operativo todo en uno para concesionarios. Hecho por dealers, respaldado por experiencia.",
  "AutoVault · The Dealership Operating System": "AutoVault · El sistema operativo para concesionarios",
  "© 2026 AutoVault. All rights reserved.": "© 2026 AutoVault. Todos los derechos reservados.",
  "Live now · First month free": "Ya disponible · Primer mes gratis",
  "Please enter your username and password.": "Ingresa tu usuario y contraseña.",
  "▲ 16% vs last month": "▲ 16% vs el mes pasado",
  "▲ 12% vs last month": "▲ 12% vs el mes pasado",
  "▲ 14% vs last month": "▲ 14% vs el mes pasado",
  "Inventory · Profit per VIN": "Inventario · Ganancia por VIN",
  "Sales Tax · Collected": "Impuesto · Recaudado",
  "Due Jul 31": "Vence 31 jul",
  "$18,240 collected for state · Quarterly filing": "$18,240 recaudados para el estado · Declaración trimestral",
  "Payroll · Base + commission": "Nómina · Base + comisión",
  "Profit & Loss · Statement": "Ganancias y pérdidas · Estado",
  "− Cost of goods": "− Costo de bienes",
  "Please enter your state and ZIP code.": "Ingresa tu estado y código postal.",
  "Please enter a valid 10-digit phone number.": "Ingresa un teléfono válido de 10 dígitos.",
  "Saving...": "Guardando...",
  "Unable to save registration.": "No se pudo guardar el registro.",
  "Failed to start registration. Please try again.": "No se pudo iniciar el registro. Inténtalo de nuevo.",
  "Failed to start registration.": "No se pudo iniciar el registro.",
  "Please submit your details first.": "Primero envía tus datos.",
  "Invalid plan selected.": "Plan no válido.",
  "Redirecting...": "Redirigiendo...",
  "Unable to create checkout session.": "No se pudo crear la sesión de pago.",
  "Checkout failed. Please try again.": "El pago falló. Inténtalo de nuevo.",
  "Checkout failed.": "El pago falló.",
  "Hey Jenna — how many vehicles are on the lot?": "Hola Jenna — ¿cuántos vehículos hay en el lote?",
  "You've got 65 vehicles on the lot, totaling $482,000 in inventory.": "Tienes 65 vehículos en el lote, con un total de $482,000 en inventario.",
  "Want me to run your profitability this week?": "¿Quieres que calcule tu rentabilidad de esta semana?",
  "Yes": "Sí",
  "This week you sold 10 cars at auction, and your net profit is $18,000. Nice work — this is shaping up to be a profitable month. Want to see this month vs. last month?": "Esta semana vendiste 10 autos en subasta, y tu ganancia neta es $18,000. Buen trabajo — este mes va camino a ser rentable. ¿Quieres ver este mes vs. el pasado?",
  "Add this deal to the vehicle inventory.": "Agrega este trato al inventario de vehículos.",
  "Added to inventory": "Agregado al inventario",
  "Done — I've added the 2021 Nissan Rogue SV and logged the numbers.": "Listo — agregué el Nissan Rogue SV 2021 y registré los números."
};

window.AV_AUTH_FLOW_EXTRA = {
  "Back to Home": "Volver al inicio",
  "Team invitation": "Invitación del equipo",
  "CPA portal invitation": "Invitación al portal CPA",
  "Join your dealership": "Únete a tu concesionario",
  "Join as CPA / Accountant": "Únete como CPA / Contador",
  "Your login email": "Tu correo de acceso",
  "Account created. Signing you in...": "Cuenta creada. Iniciando sesión...",
  "Create your password to activate your AutoVault account.":
    "Crea tu contraseña para activar tu cuenta de AutoVault.",
  "Create your password to access the read-only CPA portal for your dealership.":
    "Crea tu contraseña para acceder al portal CPA de solo lectura de tu concesionario.",
  "Checking link…": "Verificando enlace…",
  "Unable to verify link": "No se pudo verificar el enlace",
  "This invite link is invalid. Ask your admin to send a new invite.":
    "Este enlace de invitación no es válido. Pide a tu administrador que envíe una nueva invitación.",
  "This invite link expired. Ask your admin to send a new invite.":
    "Este enlace de invitación venció. Pide a tu administrador que envíe una nueva invitación.",
  "Could not verify this invite link.":
    "No se pudo verificar este enlace de invitación.",
  "Show password": "Mostrar contraseña",
  "Hide password": "Ocultar contraseña",
  "Full name": "Nombre completo",
  "Confirm password": "Confirmar contraseña",
  "Your full name": "Tu nombre completo",
  "Strong password (8+ chars)": "Contraseña segura (8+ caracteres)",
  "Re-enter password": "Vuelve a escribir la contraseña",
  "Accept invitation": "Aceptar invitación",
  "Activating...": "Activando...",
  "Already have an account? Log in": "¿Ya tienes cuenta? Inicia sesión",
  "This invite link is missing a token. Open the link from your email.":
    "Este enlace no tiene token. Abre el enlace desde tu correo.",
  "Enter your full name.": "Escribe tu nombre completo.",
  "Password must be at least 8 characters.":
    "La contraseña debe tener al menos 8 caracteres.",
  "Password needs uppercase, lowercase, a number, and a special character.":
    "La contraseña necesita mayúscula, minúscula, un número y un carácter especial.",
  "Passwords do not match.": "Las contraseñas no coinciden.",
  "Account created. Redirecting to login...":
    "Cuenta creada. Redirigiendo al inicio de sesión...",
  "Invite invalid or expired.": "Invitación inválida o vencida.",
  "Finishing setup…": "Finalizando configuración…",
  "We're confirming your account. This only takes a moment.":
    "Estamos confirmando tu cuenta. Solo toma un momento.",
  "Account Created": "Cuenta creada",
  "Welcome to AutoVault!": "¡Bienvenido a AutoVault!",
  "Your account has been created successfully.":
    "Tu cuenta se creó correctamente.",
  "Login credentials sent to": "Credenciales enviadas a",
  "Please check your inbox, and if you don't see the email, be sure to check your Spam/Junk folder.":
    "Revisa tu bandeja de entrada y, si no ves el correo, revisa también Spam/Correo no deseado.",
  "Go to Login Page": "Ir al inicio de sesión",
  "You'll stay on this page until you continue to login.":
    "Permanecerás en esta página hasta que continúes al inicio de sesión.",
  "Invalid confirmation link": "Enlace de confirmación inválido",
  "Token is missing. Please return to the landing page and try again.":
    "Falta el token. Vuelve a la página principal e inténtalo de nuevo.",
  "Could not verify purchase": "No se pudo verificar la compra",
  "Your confirmation link is invalid or expired. Please contact support.":
    "Tu enlace de confirmación es inválido o venció. Contacta a soporte.",
  "Back to Home": "Volver al inicio",
  "your email": "tu correo"
};

window.AV_CONTACT_EXTRA = {
  "Back to site": "Volver al sitio",
  "Language and theme": "Idioma y tema",
  "Switch to Spanish": "Cambiar a español",
  "Switch to English": "Cambiar a inglés",
  "Español": "Español",
  "English": "Inglés",
  "Get in touch": "Contáctanos",
  "Contact us": "Contáctanos",
  "Tell us about your dealership and we'll get right back to you.":
    "Cuéntanos sobre tu concesionario y te responderemos pronto.",
  "First name": "Nombre",
  "Last name": "Apellido",
  "Company / Dealership": "Empresa / Concesionario",
  "Email": "Correo electrónico",
  "Mobile number": "Teléfono móvil",
  "State": "Estado",
  "Select your state": "Selecciona tu estado",
  "How can we help?": "¿Cómo podemos ayudarte?",
  "Tell us what you're looking for...": "Cuéntanos qué buscas...",
  "Send message": "Enviar mensaje",
  "Sending...": "Enviando...",
  "Thanks — we'll be in touch soon!": "¡Gracias — nos pondremos en contacto pronto!"
};

window.AV_LOGIN_EXTRA = {
  "Language and theme": "Idioma y tema",
  "Switch to Spanish": "Cambiar a español",
  "Switch to English": "Cambiar a inglés",
  "Español": "Español",
  "English": "Inglés",
  "Dealership Login": "Inicio de sesión del concesionario",
  "Super Owner Login": "Inicio de sesión del propietario",
  "Welcome back": "Bienvenido de nuevo",
  "Welcome to Owner Overview": "Bienvenido al panel del propietario",
  "Sign in to your dealership dashboard.":
    "Inicia sesión en el panel de tu concesionario.",
  "Sign in to access your AutoVault dashboard.":
    "Inicia sesión para acceder a tu panel de AutoVault.",
  "Sign in as super owner to access the owner overview dashboard.":
    "Inicia sesión como propietario para acceder al panel de resumen.",
  "Username or email": "Usuario o correo",
  "Password": "Contraseña",
  "Stay signed in": "Mantener sesión iniciada",
  "Forgot password?": "¿Olvidaste tu contraseña?",
  "Sign in to dashboard": "Iniciar sesión en el panel",
  "Sign in": "Iniciar sesión",
  "Sign in to owner dashboard": "Iniciar sesión en el panel del propietario",
  "New dealership?": "¿Nuevo concesionario?",
  "Sign up here": "Regístrate aquí",
  "Secured with 256-bit encryption": "Protegido con cifrado de 256 bits",
  "Please enter your username and password.":
    "Ingresa tu usuario y contraseña."
};

window.avT = function (en) {
  if (document.documentElement.lang !== "es") return en;
  const d = window.AV_LANDING_DICT || window.AV_LANDING_EXTRA || {};
  return d[en] != null ? d[en] : en;
};
